fix: solve the problem of push external repository fail
erda-project/erda pull request #1032
Opened 2021-07-15 12:32 UTC by littlejiancc

#### What type of this PR
/kind bug

#### What this PR does / why we need it:
fix: solve the problem of push external repository fail

#### Which issue(s) this PR fixes:
https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=72245&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTI2MSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @sfwn 

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-07-15 13:33 UTC, sfwn requested changes

2021-07-15 13:33 UTC, sfwn commented on modules/gittar/auth/auth.go
> +		repoLock := models.RepoLock{Repo: repo, RwMutex: &sync.RWMutex{}}
Put mutex into repo struct is better.

2021-07-16 03:59 UTC, sfwn requested changes

2021-07-16 03:59 UTC, sfwn commented on modules/gittar/auth/auth.go
> +			repo.RwMutex = &sync.RWMutex{}
set rwmutex inside openRepository method.

2021-07-16 06:19 UTC, littlejiancc commented on modules/gittar/auth/auth.go
> +		repoLock := models.RepoLock{Repo: repo, RwMutex: &sync.RWMutex{}}
done

2021-07-16 06:20 UTC, littlejiancc commented on modules/gittar/auth/auth.go
> +			repo.RwMutex = &sync.RWMutex{}
done

2021-07-16 06:40 UTC, sfwn approved these changes

2021-07-16 06:40 UTC, merged

2021-07-16 06:41 UTC, littlejiancc commented
/cherry-pick release/1.1