fix orchestrator nil pointer dereference error
erda-project/erda pull request #1048
Opened 2021-07-16 08:32 UTC by QvodSoldier

#### What type of this PR

Add one of the following kinds:
/kind bug

#### What this PR does / why we need it:
fix deploy panic when addon config is empty

#### Which issue(s) this PR fixes:
- [nil point interface](https://erda.cloud/erda/workBench/projects/387/issues/all?id=74081&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG)
- [personal mssage](https://erda.cloud/erda/workBench/projects/387/issues/all?id=73840&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)
- [job detail](https://erda.cloud/erda/workBench/projects/387/issues/all?id=64367&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)

#### Specified Reviewers:

/assign @Effet

2021-07-16 08:54 UTC, Effet commented
it's bad to fix multiple bugs in one pr

2021-07-16 09:12 UTC, sfwn requested changes

2021-07-16 09:12 UTC, sfwn commented on modules/orchestrator/services/runtime/runtime.go
> +	createPipelineReq := &apistructs.PipelineCreateRequestV2{
@chengjoey will make a new pr for this at send side.

2021-07-16 09:16 UTC, QvodSoldier commented
> it's bad to fix multiple bugs in one pr

If split into 3 pr, I am worried that the merger cannot be completed today

2021-07-16 09:17 UTC, QvodSoldier commented
ok, i will close this pr, Re-split into two pr

2021-07-16 09:18 UTC, sfwn commented
> > it's bad to fix multiple bugs in one pr
> 
> If split into 3 pr, I am worried that the merger cannot be completed today

Feel free to open as many pr as possible, because we closed `update branch` a few days ago.

2021-07-16 09:26 UTC, closed without merging

2021-07-19 03:17 UTC, Effet commented
> because we closed `update branch` a few days ago.

it's also not good.