collector migrate
erda-project/erda pull request #106
Opened 2021-04-07 06:34 UTC by erenming

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
migrate module collector 
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Specified Reivewers:
/assgin @liuhaoyang 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation usage docs, etc.:

```docs

```

2021-04-07 06:39 UTC, sfwn requested changes

2021-04-07 06:39 UTC, sfwn commented on modules/collector/collector.go
> +	"github.com/labstack/echo"
Please distinguish github.com/erda-project/xxx and others.

The order it should be like this:
- standard library
- third-party library
- erda-project related library

2021-04-07 08:56 UTC, liuhaoyang requested changes
Please resolve conflicts, and add sufficient unit tests.

2021-04-08 09:19 UTC, recallsong commented on modules/monitor/core/collector/collector.go
> +func (m *define) Service() []string      { return []string{"metrics-collector"} }
Services

2021-04-09 11:53 UTC, liuhaoyang approved these changes

2021-04-10 07:03 UTC, liuhaoyang approved these changes

2021-04-10 07:03 UTC, liuhaoyang approved these changes

2021-04-10 07:07 UTC, sfwn approved these changes

2021-04-10 07:07 UTC, merged