Add steve API and bundle
erda-project/erda pull request #1099
Opened 2021-07-21 02:32 UTC by CraigMChen

#### What type of this PR

/kind feature

#### What this PR does / why we need it:

1. Integrate steve server in cmp.
2. Add bundle for steve server.

#### Specified Reviewers:

/assign @johnlanni

2021-07-21 03:08 UTC, dspo commented on apistructs/steve.go
> +// SteveCollection 用于接收steve server返回的集合类型的数据（一次返回多条数据）
It is best to comment in English

2021-07-21 03:16 UTC, dspo commented on bundle/steve_test.go
> +//import (
do not submit invalid code

2021-07-21 03:17 UTC, dspo commented on modules/cmp/endpoints/steve.go
> +	req := apistructs.ClusterEvent{}
`var req apistructs.ClusterEvent`

2021-07-21 03:28 UTC, dspo commented on modules/cmp/endpoints/steve.go
> +	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
the `Decode` will be panic if `r.Body == nil`

2021-07-21 03:37 UTC, dspo commented on modules/cmp/endpoints/steve.go
> +		return httpserver.HTTPResponse{Status: http.StatusBadRequest, Content: errstr}, nil
```go
err = errors.Wrap(err, "failed to decode clusterhook request")
logrus.Error(err)
return httpserver.HTTPResponse(Status: http.StatusBadRequest, Content: err.Error()), nil
```
reference: https://yuque.antfin.com/dice/zs3zid/dkr3ym#456d29ef
"The action log uses the following format: failed to do something"

2021-07-21 03:43 UTC, dspo commented on modules/cmp/initialize.go
> +				httpclient.WithTimeout(30*time.Second, time.Second*60),
To unify the format, either all are `time.Second * num`, or all are `num * time.Second`
```go
httpclient.WithTiemeout(time.Second * 30, time.Second * 60)
```

2021-07-21 03:45 UTC, dspo commented on modules/cmp/initialize.go
> +	server.Router().PathPrefix("/k8s/clusters/{clusterName}").Handler(ep.SteveAggregator)
magic value `"/k8s/clusters/{clusterName}"`

2021-07-22 08:00 UTC, CraigMChen commented on modules/cmp/steve/aggregator.go
> +}
已添加补偿机制

2021-07-26 02:17 UTC, liuhaoyang requested changes
New apis should be defined using proto

2021-07-26 02:20 UTC, liuhaoyang submitted a review, later dismissed

2021-07-26 02:20 UTC, liuhaoyang commented on modules/cmp/initialize.go
>  	server := httpserver.New(conf.ListenAddr())
The new module should use Erda infra instead of obsolete endpoints

2021-08-11 12:05 UTC, johnlanni requested changes

2021-08-16 12:03 UTC, johnlanni approved these changes

2021-08-16 12:11 UTC, johnlanni commented
/approve

2021-08-16 12:27 UTC, johnlanni commented
/approve

2021-08-16 12:27 UTC, merged