cmp component protocol
erda-project/erda pull request #1104
Opened 2021-07-21 06:30 UTC by bugaolengdeyuxiaoer

#### What type of this PR

Add one of the following kinds:
/kind feature 

#### What this PR does / why we need it:
add cmp component protocol

#### Specified Reviewers:

/assign @your-reviewer
@johnlanni #### Need cherry-pick to release versions?

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-07-21 12:51 UTC, Effet requested changes

2021-07-21 12:51 UTC, Effet commented on modules/openapi/component-protocol/scenarios/cmp-dashboard/components/cpuTable/model.go
> +type RowItem struct {
table component struct already define in framework code, is it a table component?

2021-07-21 12:51 UTC, Effet commented on modules/openapi/component-protocol/scenarios/cmp-dashboard/components/cpuTable/model.go
> +type RowItem struct {
modules/openapi/component-protocol/component_spec/table/spec.go

2021-08-04 11:59 UTC, johnlanni requested changes

2021-09-01 17:43 UTC, closed without merging