actionagent callback stderr if match regexp
erda-project/erda pull request #1116
Opened 2021-07-21 11:31 UTC by chengjoey

#### What type of this PR

Add one of the following kinds:
/kind bug

#### What this PR does / why we need it:
actionagent callback stderr if match regexp in every line

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/workBench/projects/387/issues/all?id=70728&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=TASK)

2021-07-21 14:05 UTC, sfwn commented
Give me a screenshot about it.

2021-07-21 14:13 UTC, sfwn requested changes

2021-07-21 14:13 UTC, sfwn commented on modules/actionagent/file_watch.go
> +		_ = recover()
log when recover

2021-07-21 14:13 UTC, sfwn commented on modules/actionagent/file_watch.go
> +		reg := regexp.MustCompile(regexpList[i])
Compile all regexps once at very beginning.

2021-07-21 14:13 UTC, sfwn commented on modules/actionagent/step_prepare.go
> +	_ = json.Unmarshal([]byte(envStdErrRegexpStr), &agent.StdErrRegexpList)
handler errors correctly.

2021-07-22 01:40 UTC, chengjoey commented
> Give me a screenshot about it.

pipeline.yml:
![image](https://user-images.githubusercontent.com/30427474/126579615-1d188adf-27cf-4d4d-abdb-80a66bcc1856.png)

result:
![image](https://user-images.githubusercontent.com/30427474/126579638-8e274b96-0d7f-471e-9574-1e1f590c126e.png)

2021-07-22 12:16 UTC, sfwn requested changes

2021-07-22 12:16 UTC, sfwn commented on build/dockerfiles/Dockerfile-action-agent
> +FROM registry.cn-hangzhou.aliyuncs.com/terminus/terminus-golang:1.14 AS compile
Update base image as others.

2021-07-26 01:41 UTC, sfwn approved these changes

2021-07-26 01:42 UTC, merged