Update component protocol image src keys
erda-project/erda pull request #1128
Opened 2021-07-22 09:51 UTC by shuofan

#### What type of this PR
feature

#### What this PR does / why we need it:
frontend maintains config images map, use key instead of address.

#### Specified Reviewers:

/assign @Effet @sfwn

2021-07-22 11:58 UTC, Effet requested changes

2021-07-22 11:58 UTC, Effet commented on modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myProjectList/render.go
> +		PrefixImg:   "/frontImg_default_project_icon",
redundant prefix "/"

2021-07-22 12:11 UTC, shuofan commented on modules/openapi/component-protocol/scenarios/home-page-sidebar/components/myProjectList/render.go
> +		PrefixImg:   "/frontImg_default_project_icon",
done

2021-07-23 07:53 UTC, Effet approved these changes

2021-07-23 07:53 UTC, Effet commented
/approve

2021-07-23 07:53 UTC, merged