move update pipeline status from reconcile to listen
erda-project/erda pull request #1143
Opened 2021-07-23 09:14 UTC by chengjoey

#### What type of this PR

Add one of the following kinds:
/kind bug

#### What this PR does / why we need it:
move update pipeline status from reconcile to listen
avoid concurrent update pipeline status

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/workBench/projects/387/issues/all?id=67613&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzEsNDY3XSwic3RhdGVCZWxvbmdzIjpbIk9QRU4iLCJXT1JLSU5HIiwiUkVPUEVOIiwiUkVTT0xWRUQiLCJXT05URklYIl0sImFzc2lnbmVlSURzIjpbIjU1IiwiMTAwMTIwNSIsIjkyIiwiMTAwMDQzNiIsIjEwMDA1NjAiLCIxMDAxMjYxIiwiMTAwMTA3MyIsIjEwMDA4MDUiLCIxMDAwODMyIl0sImZpbmlzaGVkQXRTdGFydEVuZCI6W251bGwsMTYyNzIyODc5OTk5OV19&issueGantt__urlQuery=eyJ0b3RhbCI6MTYsInBhZ2VObyI6MSwicGFnZVNpemUiOjIwMCwiaXNzdWVWaWV3R3JvdXBWYWx1ZSI6ImdhbnR0IiwiSXNzdWVUeXBlIjoiQUxMIn0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImdhbnR0IiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG)

2021-07-30 07:34 UTC, sfwn requested changes

2021-07-30 07:34 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/listen.go
> +					if p.Status.IsEndStatus() {
panic here if err is not empty.

2021-07-30 07:34 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/listen.go
> +					if p.Status != apistructs.PipelineStatusRunning {
abstract to a method

2021-08-03 02:05 UTC, sfwn requested changes

2021-08-03 02:05 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/listen.go
> +						panic(err)
you should recover panic.

2021-08-03 02:05 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/listen.go
> +						panic(err)
how about db server error. you should retry.

2021-08-03 02:05 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/listen.go
> +					if !p.Status.IsRunningStatus() {
abstract a method.

2021-08-03 07:03 UTC, sfwn requested changes

2021-08-03 07:03 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/listen.go
> +	pipelineWithTasks, err := r.dbClient.GetPipelineWithTasks(pipelineID)
you need check status.

see `r.reconcileAgain(pipelineID)`

2021-08-03 07:03 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/reconcile.go
> +				err = r.reconcile(snippetCtx, sp.ID)
where to updateStatusBeforeReconcile for snippet pipeline?

2021-08-03 07:14 UTC, sfwn requested changes

2021-08-03 07:14 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/listen.go
> +	r.teardownPipeline(ctx, pipelineWithTasks)
split teardownPipeline into `teardownCurrentReconcile` and `teardownPipeline`

2021-08-03 07:26 UTC, chengjoey commented on modules/pipeline/pipengine/reconciler/listen.go
> +						if err != nil {
shouldn`t get not found error

2021-08-04 03:14 UTC, sfwn requested changes

2021-08-04 03:14 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/teardown.go
> +	r.teardownCurrentReconcile(ctx, p)
invoke seperately

2021-08-04 03:14 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/teardown.go
> +	if p.Pipeline.Status.IsEndStatus() {
if not end status, fast return firstly.

2021-08-04 03:14 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/teardown.go
> +	if p.Pipeline.Status.IsEndStatus() {
now there are so many needless git changes like below.

2021-08-04 07:47 UTC, sfwn approved these changes

2021-08-04 08:29 UTC, sfwn commented
/approve

2021-08-04 08:29 UTC, merged

2021-08-04 08:32 UTC, chengjoey commented
/cherry-pick release/1.2