add provider named extention in dicehub
erda-project/erda pull request #1197
Opened 2021-07-28 12:38 UTC by ZLValien

#### What type of this PR

/kind feature

#### What this PR does / why we need it:

add provider named extention in dicehub

2021-07-28 15:53 UTC, sfwn commented
ci failed.

2021-07-30 05:54 UTC, sfwn approved these changes

2021-07-30 05:54 UTC, sfwn commented on pkg/common/apis/header.go
> +	return GetHeader(ctx, "Lang")
lower case in grpc.

2021-07-30 06:58 UTC, ZLValien commented on pkg/common/apis/header.go
> +	return GetHeader(ctx, "Lang")
done

2021-08-03 01:49 UTC, Effet requested changes

2021-08-03 01:49 UTC, Effet commented on modules/dicehub/extension/db/extension.go
> +		swaggerData, _ := yaml.YAMLToJSON([]byte(ext.Swagger))
error should be checked

2021-08-03 03:11 UTC, ZLValien commented on modules/dicehub/extension/db/extension.go
> +		swaggerData, _ := yaml.YAMLToJSON([]byte(ext.Swagger))
done

2021-08-03 03:33 UTC, sfwn approved these changes

2021-08-03 03:35 UTC, merged

2021-08-17 06:54 UTC, ZLValien commented
/cherry-pick release/1.2