pull action by github
erda-project/erda pull request #1300
Opened 2021-08-04 08:12 UTC by ZLValien

#### What type of this PR

/kind feature

#### What this PR does / why we need it:

if version of extension is URL. pull action form URL

2021-08-04 08:13 UTC, sfwn commented
Give us a sample of pipeline.yml.

2021-08-04 08:14 UTC, sfwn commented
How about the speed? We recommend use app gittar url, not github. Test it please.

2021-08-04 08:50 UTC, ZLValien commented
> How about the speed? We recommend use app gittar url, not github. Test it please.
local:
https://github.com/ZLValien/erda-actions    10s
https://erda.hkci.terminus.io/integration/dop/zzzz/action  2s

2021-08-05 01:31 UTC, Effet commented
if not related about github, please amend your pr title @ZLValien

2021-08-05 03:08 UTC, ZLValien commented
this can be tested
POST http://openapi.dev.terminus.io/api/extensions/actions/search
body:{
    "yamlFormat":false,
    "extensions":["test2@https://erda.hkci.terminus.io/integration/dop/zzzz/action"]
}

2021-08-05 03:26 UTC, kakj-go commented on modules/dicehub/service/extension/git_test.go
> +//func Test_pullgit(t *testing.T) {
if can not test getGit func, remove this test file

2021-08-05 03:26 UTC, kakj-go commented on modules/dicehub/service/extension/git.go
> +	command := exec.Command("sh", "-c", "git init")
git init should after cd temp dir

2021-08-05 03:26 UTC, kakj-go commented on modules/dicehub/service/extension/git.go
> +func getGit(d string, file ...string) ([]string, error) {
change func name like `getGitFileContents`

2021-08-05 03:52 UTC, Effet commented
still bad title, please explain what exactly you did.

2021-08-06 02:29 UTC, ZLValien commented
https://erda.dev.terminus.io/terminus/dop/projects/2/apps/117/repo/tree/feature/sonar/pipeline.yml

test

2021-08-06 05:48 UTC, sfwn requested changes

2021-08-09 06:18 UTC, ZLValien commented on modules/dicehub/service/extension/extension.go
> +		go func(fnm string) {
Concurrently pull 100 small warehouses (10KB each), the test is successful

Concurrently pull 30 large warehouses (100MB each), the interface is timed out, the “defer” logic is not entered, so the folder is not deleted, the test is fail

2021-08-10 02:02 UTC, sfwn approved these changes

2021-08-10 02:02 UTC, sfwn commented
/approve

2021-08-10 02:02 UTC, merged