fix : create extension false when init provider
erda-project/erda pull request #1488
Opened 2021-08-17 11:27 UTC by ZLValien

#### What type of this PR

/kind bug

#### What this PR does / why we need it:

The read file address does not match the actual address

2021-08-17 11:53 UTC, sfwn requested changes

2021-08-17 11:53 UTC, sfwn commented on modules/dicehub/extension/provider.go
> +		err := p.extensionService.InitExtension("/app/dicehub-extension")
extensions

2021-08-17 13:08 UTC, ZLValien commented on modules/dicehub/extension/provider.go
> +		err := p.extensionService.InitExtension("/app/dicehub-extension")
done

2021-08-18 05:42 UTC, sfwn approved these changes

2021-08-19 03:22 UTC, sfwn approved these changes

2021-08-19 03:22 UTC, sfwn commented
/approve

2021-08-19 03:23 UTC, merged