pipeline-aop refactor to provider
erda-project/erda pull request #1546
Opened 2021-08-24 09:50 UTC by ZLValien

#### What type of this PR

/kind feature

#### What this PR does / why we need it:

refactor aop.

now, the tuneType and tuneTrigger of plugins is  defined in pipeline.yml。

2021-08-30 06:05 UTC, sfwn requested changes

2021-08-30 06:05 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/queuemanage/manager/define.go
> +func New(pluginsManage *plugins_manage.PluginsManage, ops ...Option) types.QueueManager {
use ops at least.

2021-08-30 06:05 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/queuemanage/queue/define.go
> +func New(pq *apistructs.PipelineQueue, pm *plugins_manage.PluginsManage, ops ...Option) *defaultQueue {
so ugly.

2021-08-30 06:05 UTC, sfwn commented on modules/pipeline/providers/aop/plugins/pipeline/apitest_report/plugin.go
> +		err := plugins_manage.RegisterTunePointToTuneGroup(p.Cfg.TuneType, tuneTrigger, New())
Use `aop.Register` and register to pkg level variables.

2021-08-30 06:05 UTC, sfwn commented on modules/pipeline/providers/aop/README.md
> +// TuneTriggerChains 保存流水线所有触发时机下的调用链
remove codes if wrong.

2021-08-31 06:28 UTC, sfwn requested changes

2021-08-31 06:28 UTC, sfwn commented on conf/pipeline/pipeline.yaml
> +        - "echo"
I think now we can remove useless `echo` plugin

2021-08-31 06:28 UTC, sfwn commented on conf/pipeline/pipeline.yaml
> +
no need new line.

2021-08-31 06:28 UTC, sfwn commented on modules/pipeline/aop/context.go
> -// Copyright (c) 2021 Terminus, Inc.
DO NOT delete these files.

2021-08-31 06:28 UTC, sfwn commented on modules/pipeline/providers/aop/plugins/pipeline/apitest_report/plugin.go
> +	TuneType    aoptypes.TuneType      `file:"tune_type"`
useless configs?

2021-08-31 07:34 UTC, ZLValien commented on cmd/pipeline/main.go
> +	_ "github.com/erda-project/erda/modules/pipeline/providers/aop/plugins/all"
if all.go add to  pkg `github.com/erda-project/erda/modules/pipeline/providers/aop` will  cycle import.
I add it to `github.com/erda-project/erda/modules/pipeline`

2021-09-01 07:12 UTC, sfwn requested changes

2021-09-01 08:26 UTC, sfwn requested changes

2021-09-01 08:26 UTC, sfwn commented on modules/pipeline/aop/aoptypes/tunegroup.go
> +type TunePointNameGroup map[TuneType]map[TuneTrigger][]string
Move this struct definition to where it used. Here is strange.

2021-09-01 08:26 UTC, sfwn commented on modules/pipeline/aop/aoptypes/tunegroup.go
> +// GetTuneChainByTypeAndTrigger By TuneType and TuneTrigger return TuneChain
`return tuneChain by xxx`

let your words smooth.

2021-09-01 08:26 UTC, sfwn commented on modules/pipeline/aop/plugins/pipeline/precheck_before_pop/plugin.go
>  func New() *Plugin { return &Plugin{} }
use provider struct to implements this interface.

2021-09-01 15:57 UTC, sfwn requested changes

2021-09-01 15:57 UTC, sfwn commented on modules/pipeline/aop/register.go
> +		panic("provider name invaild, tuneType: " + string(point.Type()) + ", name: " + point.Name())
tell the reason

2021-09-01 15:57 UTC, sfwn commented on modules/pipeline/aop/plugins/pipeline/apitest_report/plugin.go
> +func New() *provider { return &provider{} }
No need exported func `New()`.
`aop.NewProviderNameByPluginName(&provider{})` is enough.

2021-09-01 15:57 UTC, sfwn commented on modules/pipeline/aop/plugins/pipeline/apitest_report/plugin.go
> +type provider struct {
move struct define to beginning, the same as `Plugin` before.

2021-09-01 15:57 UTC, sfwn commented on modules/pipeline/aop/plugins/pipeline/apitest_report/plugin.go
> +	err := aop.RegisterTunePoint(p)
if err := xxx; err != nil

2021-09-01 15:57 UTC, sfwn commented on modules/pipeline/aop/register.go
> +	// Convert TunePointNameGroup to TuneGroup
Move to func comment.

2021-09-01 15:57 UTC, sfwn commented on modules/pipeline/aop/register.go
> +		return errors.New("tunePoint is existed, tuneType: " + string(tunePoint.Type()) + ", Name: " + tunePoint.Name())
failed to register xxx, tunePoint is already exist, xxx

2021-09-01 15:57 UTC, sfwn commented on modules/pipeline/aop/register.go
> +func ConvertTuneGroup(gp TunePointNameGroup) error {
no need export this func.

2021-09-01 15:57 UTC, sfwn commented on modules/pipeline/aop/register.go
> +func ConvertTuneGroup(gp TunePointNameGroup) error {
bad name.
`handleTuneConfigs`

2021-09-01 15:57 UTC, sfwn commented on modules/pipeline/aop/provider.go
> +type TunePointNameGroup map[aoptypes.TuneType]map[aoptypes.TuneTrigger][]string
TuneConfigs

2021-09-02 05:36 UTC, sfwn approved these changes

2021-09-02 05:36 UTC, sfwn commented
/approve

2021-09-02 05:36 UTC, merged