Pipeline tasks are only created in the database at runtime
erda-project/erda pull request #1552
Opened 2021-08-25 02:38 UTC by kakj-go

#### What type of this PR

/kind feature

#### What this PR does / why we need it:
In the automated test scenario, a large number of pipelines and tasks will be created. If they are created in the database before execution as before, it will cause a lot of pressure on the pipeline, so the creation process lags, and it is created during execution.

#### Which issue(s) this PR fixes:
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=58495&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)

2021-08-30 07:11 UTC, sfwn requested changes

2021-08-30 07:11 UTC, sfwn commented on modules/pipeline/services/pipelinesvc/create.go
> +func (s *PipelineSvc) createPipelineGraphStage(p *spec.Pipeline, pipelineYml *pipelineyml.PipelineYml, txSession *xorm.Session) (stages []*spec.PipelineStage, err error) {
use `dbclient.Session`, which wrapped `xorm.Session'

2021-08-30 07:11 UTC, sfwn commented on modules/pipeline/services/pipelinesvc/create.go
> +		if err := s.dbClient.CreatePipelineStage(ps, dbclient.WithTxSession(txSession)); err != nil {
passed with dbclient.SessionOptions

2021-08-30 07:11 UTC, sfwn commented on modules/pipeline/services/pipelinesvc/create.go
> +func (s *PipelineSvc) MergePipelineYmlTasks(pipelineYml *pipelineyml.PipelineYml, dbTasks []spec.PipelineTask, p *spec.Pipeline, dbStages []spec.PipelineStage, passedDataWhenCreate *task_extensions.P
Add comments.

2021-09-01 01:52 UTC, kakj-go commented on modules/pipeline/endpoints/permission.go
> +	stages, err := e.dbClient.ListPipelineStageByPipelineID(p.ID)
Yes, it need to query all stages later

2021-09-01 01:55 UTC, kakj-go commented on modules/pipeline/initialize.go
> +		CronNotExecuteCompensate:                pipelineSvc.CronNotExecuteCompensateById,
Yes, I added todo and then consider how to refactor

2021-09-01 02:03 UTC, kakj-go commented on modules/pipeline/pipengine/reconciler/define.go
> +	CronNotExecuteCompensate                func(id uint64) error
Yes, I added todo and then consider how to refactor

2021-09-01 02:08 UTC, kakj-go commented on modules/pipeline/pipengine/reconciler/reconcile.go
> +func (r *Reconciler) MergeDBTasks(pipeline *spec.Pipeline) ([]*spec.PipelineTask, error) {
Some methods require pipeline information

2021-09-01 16:47 UTC, sfwn reviewed
I will review it again tomorrow.

2021-09-02 02:21 UTC, sfwn approved these changes

2021-09-02 02:21 UTC, sfwn commented
/approve

2021-09-02 02:22 UTC, merged