fix: solve the problem of incorrect execution time of cron
erda-project/erda pull request #1555
Opened 2021-08-25 06:10 UTC by littlejiancc

#### What type of this PR
/kind bug

#### What this PR does / why we need it:
fix: solve the problem of incorrect execution time of cron

#### Which issue(s) this PR fixes:
[【流水线】定时任务执行时间在某一些情况下执行时间不正确](https://erda.cloud/erda/dop/projects/387/issues/all?id=210903&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       解决定时任务执行时间不正确问题       |
| 🇨🇳 中文    |     solve the problem of incorrect execution time of cron         |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-08-25 07:08 UTC, sfwn requested changes

2021-08-25 07:08 UTC, sfwn commented on pkg/cron/cron.go
> +			now = c.now()
add sample for this change.

2021-08-25 07:09 UTC, sfwn commented
Check the version this bug imported.
And fixed to these affected versions.

2021-08-25 07:26 UTC, littlejiancc commented on pkg/cron/cron.go
> +			now = c.now()
done

2021-08-26 15:56 UTC, sfwn submitted a review, later dismissed

2021-08-30 11:08 UTC, sfwn approved these changes

2021-08-30 11:09 UTC, merged

2021-08-30 11:10 UTC, littlejiancc commented
/cherry-pick release/1.2