read all unread mbox with one click
erda-project/erda pull request #1593
Opened 2021-08-30 06:26 UTC by QvodSoldier

#### What type of this PR
/kind feature

#### What this PR does / why we need it:
add feature: read all unread mbox with one click

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=202613&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=REQUIREMENT)

#### Specified Reviewers:

/assign @Effet

2021-08-30 09:38 UTC, Effet requested changes

2021-08-30 09:38 UTC, Effet commented on modules/core-services/dao/mbox.go
> +func (client *DBClient) OneClickRead(orgID int64, userID string) error {
`ReadAll(` is better

2021-08-30 09:38 UTC, Effet commented on modules/core-services/endpoints/endpoints.go
> +		{Path: "/api/mboxs/actions/one-click-read", Method: http.MethodPost, Handler: e.OneClickRead},
`read-all` is better

2021-08-31 01:42 UTC, QvodSoldier commented on modules/core-services/dao/mbox.go
> +func (client *DBClient) OneClickRead(orgID int64, userID string) error {
done

2021-08-31 01:42 UTC, QvodSoldier commented on modules/core-services/dao/mbox.go
> +func (client *DBClient) OneClickRead(orgID int64, userID string) error {
done

2021-08-31 01:42 UTC, QvodSoldier commented on modules/core-services/endpoints/endpoints.go
> +		{Path: "/api/mboxs/actions/one-click-read", Method: http.MethodPost, Handler: e.OneClickRead},
done

2021-08-31 03:29 UTC, Effet approved these changes

2021-08-31 03:29 UTC, Effet commented
/approve

2021-08-31 04:08 UTC, merged