support new Erda image version
erda-project/erda pull request #1597
Opened 2021-08-30 08:54 UTC by ZLValien

#### What type of this PR

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:
image version from "1.3-xxxxxx-xxxx" to "1.3.0-alpha-xxxxxxx-xxxxxx"
update Check()

https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=217915&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDgzMiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK

2021-08-31 05:56 UTC, Effet requested changes

2021-08-31 05:56 UTC, Effet commented on apistructs/extention.go
> +	newSemVersion, _ := semVersion.SetPrerelease("")
why you eat the error?

2021-09-02 07:08 UTC, hoozecn commented
/approve

2021-09-02 07:09 UTC, hoozecn approved these changes

2021-09-03 02:45 UTC, sfwn commented
/approve

2021-09-03 02:45 UTC, merged