add docker registry username/password
erda-project/erda pull request #1628
Opened 2021-09-01 02:58 UTC by pipipipipi43

#### What type of this PR

Add one of the following kinds:

/kind feature

#### What this PR does / why we need it:

Added docker username and password

#### Which issue(s) this PR fixes:

- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=210067&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDgwNSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=TASK)

#### Specified Reviewers:

/assign @sfwn 

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |     Support third-party docker registry        |
| 🇨🇳 中文    |   支持第三方 docker registry          |

2021-09-01 03:00 UTC, pipipipipi43 commented
related erda pr: https://github.com/erda-project/erda-actions/pull/175

2021-09-01 11:10 UTC, kakj-go commented on modules/pipeline/services/pipelinesvc/secret.go
> +func AddRegistryLabel(r map[string]string, clusterInfo apistructs.ClusterInfoData) map[string]string {
add method annotation

2021-09-01 16:40 UTC, sfwn requested changes

2021-09-01 16:40 UTC, sfwn commented on apistructs/cluster_info.go
> +	REGISTRY_USERNAME       ClusterInfoMapKey = "REGISTRY_USERNAME"       // registry 用户名
english comment

2021-09-01 16:40 UTC, sfwn commented on apistructs/cluster_info.go
> +	REGISTRY_USERNAME       ClusterInfoMapKey = "REGISTRY_USERNAME"       // registry 用户名
You should ensure SRE will inject these two fields.
Any related issues?

2021-09-01 16:40 UTC, sfwn commented on modules/pipeline/services/pipelinesvc/secret.go
> +		"bp.repo.prefix":           "", // 兼容用户 pipeline.yml 里写的 ((bp.repo.prefix))
english comment if adjusted.

2021-09-01 16:40 UTC, sfwn commented on modules/pipeline/services/pipelinesvc/secret.go
> +func AddRegistryLabel(r map[string]string, clusterInfo apistructs.ClusterInfoData) map[string]string {
format: AddRegistryLabel xxx
begin with method name.

2021-09-02 03:05 UTC, sfwn approved these changes

2021-09-02 03:05 UTC, sfwn commented
/approve

2021-09-02 03:05 UTC, merged