support upper layer customize pipeline namespace
erda-project/erda pull request #1641
Opened 2021-09-01 12:15 UTC by chengjoey

#### What type of this PR

Add one of the following kinds:
/kind feature

#### What this PR does / why we need it:
support upper layer customize pipeline namespace

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=58451&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASKe)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  support customize namespace            |
| 🇨🇳 中文    |   支持上层自定义流水线命名空间           |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-09-01 16:37 UTC, sfwn requested changes

2021-09-01 16:37 UTC, sfwn commented on apistructs/job.go
> +	IsCustomNamespace bool                   `json:"isCustomNamespace"` // if isCustomNamespace is true, resource gc should be attention don't delete namespace
More clearly.
`IsPipelineControlledNs`.

2021-09-01 16:37 UTC, sfwn commented
How about other executor's namespace gc logic?

2021-09-02 01:53 UTC, chengjoey commented
> How about other executor's namespace gc logic?

add delete ns Judgment logic in k8sflink `create` func and k8sspark

2021-09-02 02:48 UTC, sfwn requested changes

2021-09-02 02:48 UTC, sfwn commented on apistructs/job.go
> +	IsPipelineControlledNs bool                   `json:"IsPipelineControlledNs"` // if IsPipelineControlledNs is true, resource gc should be attention don't delete namespace
if IsPipelineControlledNs is true => false

2021-09-02 02:48 UTC, sfwn commented on apistructs/job.go
> +	IsPipelineControlledNs bool                   `json:"IsPipelineControlledNs"` // if IsPipelineControlledNs is true, resource gc should be attention don't delete namespace
Old existed records' `IsPipelineControlledNs` is default false, will cause gc skipped.

2021-09-02 02:51 UTC, sfwn commented on apistructs/job.go
> +	IsPipelineControlledNs bool                   `json:"IsPipelineControlledNs"` // if IsPipelineControlledNs is true, resource gc should be attention don't delete namespace
Change to `NotPipelineControlledNs`

2021-09-02 05:53 UTC, sfwn approved these changes

2021-09-02 05:53 UTC, sfwn commented
/approve

2021-09-02 05:53 UTC, merged