add aop autotest-plan-before
erda-project/erda pull request #1650
Opened 2021-09-02 07:26 UTC by ZLValien

#### What type of this PR

/kind feature

#### What this PR does / why we need it:

when autotest-plan is executed,report configuration

2021-09-02 11:55 UTC, sfwn requested changes

2021-09-02 11:55 UTC, sfwn commented on modules/pipeline/aop/plugins/pipeline/testplan_before/plugin.go
> +	p.Bundle = bundle.New(bundle.WithDOP())
pipeline is not allowed to invoke dop.

2021-09-02 11:55 UTC, sfwn commented on modules/pipeline/aop/plugins/pipeline/testplan_before/plugin.go
> +	p.Bundle = bundle.New(bundle.WithDOP())
use event to decouple.

2021-09-02 12:12 UTC, ZLValien commented on modules/pipeline/aop/plugins/pipeline/testplan_before/plugin.go
> +		if v.Ns == ctx.SDK.Pipeline.PipelineExtra.Extra.ConfigManageNamespaces[0] {
configManageNamespaces":["autotest^scope-project-autotest-testcase^scopeid-x^xxxxxxx"]
Now it has only one

2021-09-03 06:01 UTC, kakj-go commented on modules/pipeline/aop/plugins/pipeline/testplan_before/plugin.go
> +	CmsService pb.CmsServiceServer `autowired:"erda.core.pipeline.cms.CmsService"`
not used

2021-09-03 06:01 UTC, kakj-go commented on modules/pipeline/aop/plugins/pipeline/testplan_before/plugin.go
> +	testPlanID, err := checkPipelineYmlName(ctx.SDK.Pipeline.PipelineYmlName)
hava apistructs.PipelineSourceAutoTestPlan prefix just enough

2021-09-06 01:45 UTC, sfwn approved these changes

2021-09-06 01:45 UTC, merged