Feature/pipeline trigger
erda-project/erda pull request #1665
Opened 2021-09-03 06:41 UTC by pipipipipi43

#### What type of this PR

Add one of the following kinds:
/kind feature

#### What this PR does / why we need it:

Added pipeline trigger syntax and expression

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDA4MDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D)

2021-09-03 07:17 UTC, Effet submitted a review, later dismissed

2021-09-03 07:17 UTC, Effet commented on apistructs/pipeline_yml.go
> +	Filter    map[string]string `yaml:"filter,omitempty" json:"filter,omitempty"`
I think `Event` is better than`EventName`.

2021-09-03 07:17 UTC, Effet commented on apistructs/pipeline_yml.go
> +	Filter    map[string]string `yaml:"filter,omitempty" json:"filter,omitempty"`
And why Filter is a map, can you describe an example?

2021-09-06 02:48 UTC, sfwn requested changes

2021-09-06 02:48 UTC, sfwn commented on pkg/parser/pipelineyml/samples/trigger.yml
> +version: "1.1"
adjust to latest yaml grammar.

2021-09-06 13:35 UTC, kakj-go commented on apistructs/pipeline_yml.go
> +	Trigger    []*PipelineTrigger `json:"triggers,omitempty"`
Trigger => Triggers

2021-09-06 13:35 UTC, kakj-go commented on modules/pipeline/precheck/precheck.go
> +		for _, val := range y.Spec().Trigger {
same like
```golang
if event.On != "" && len(event.Filter) > 0 {
    triggerLabels[event.On] = event.Filter
}
```

2021-09-06 13:35 UTC, kakj-go commented on modules/pipeline/precheck/precheck.go
> +	fmt.Println("init preCheck triggerLables: ", triggerLables)
remove

2021-09-08 07:24 UTC, sfwn requested changes

2021-09-08 07:24 UTC, sfwn commented on pkg/parser/pipelineyml/pipelineyml.go
> +	// triggerLabel
triggerLabels xxx

2021-09-08 07:24 UTC, sfwn commented on pkg/parser/pipelineyml/samples/trigger.yml
> +  - "on": issue
ugly quote around `on`.

2021-09-08 07:24 UTC, sfwn commented on pkg/parser/pipelineyml/visitor_labels.go
> +// yaml 全局文本替换
english comment

2021-09-08 07:47 UTC, pipipipipi43 commented on pkg/parser/pipelineyml/pipelineyml.go
> +	// triggerLabel
done

2021-09-08 07:47 UTC, pipipipipi43 commented on pkg/parser/pipelineyml/visitor_labels.go
> +// yaml 全局文本替换
done

2021-09-08 07:54 UTC, pipipipipi43 commented on pkg/parser/pipelineyml/samples/trigger.yml
> +  - "on": issue
todo commit at  pipeline.Spec

2021-09-08 08:56 UTC, sfwn approved these changes

2021-09-08 08:56 UTC, sfwn commented
/approve

2021-09-08 08:56 UTC, merged