Orchestrator refactor phase 2: delete runtime api
erda-project/erda pull request #1730
Opened 2021-09-08 03:19 UTC by hoozecn

#### What type of this PR

The Delete runtime api must be refactor too since it shared the same url with GetRuntime api

Add one of the following kinds:
/kind feature

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

- [「重构」orchestrator runtime 部分改为使用proto定义](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=217750&issueFilter__urlQuery=eyJ0aXRsZSI6IumHjeaehCJ9&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=TASK)

#### Specified Reviewers:

/assign @sfwn

2021-09-08 11:02 UTC, sfwn requested changes

2021-09-08 11:02 UTC, sfwn commented on modules/orchestrator/components/runtime/runtime.service.go
> +// Delete 标记应用实例删除
All new comments should be English.

2021-09-08 12:47 UTC, hoozecn commented on modules/orchestrator/components/runtime/runtime.service.go
> +// Delete 标记应用实例删除
Oops. Done

2021-09-09 05:20 UTC, sfwn approved these changes

2021-09-09 05:40 UTC, sfwn commented
/approve

2021-09-09 05:40 UTC, merged