fix(scheduler): support to create the volume of ds when use bind in YAML
erda-project/erda pull request #176
Opened 2021-04-13 11:18 UTC by Muzry

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

fix(scheduler): support to create the volume of ds when use bind in YAML

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Specified Reivewers:
/assgin @luobily @sixther-dc @johnlanni 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation usage docs, etc.:

```docs

```

2021-04-14 03:08 UTC, Muzry commented
#180

2021-04-15 07:00 UTC, luobily requested changes

2021-04-15 07:00 UTC, luobily commented on modules/scheduler/executor/plugins/k8s/daemonset.go
> +	secrets, err := k.CopyDiceSecrets("secret", service.Namespace)
modify dice to erda

2021-04-15 08:12 UTC, luobily approved these changes
lgtm

2021-04-15 08:12 UTC, merged