modify set Cookie's Domain
erda-project/erda pull request #178
Opened 2021-04-13 12:39 UTC by QvodSoldier

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
In the login process, we need set cookie to subdomain(e.g. .app.xxx.com) rather than .xxx.com

#### Specified Reivewers:
/assgin @Effet

2021-04-13 12:49 UTC, Effet approved these changes

2021-04-13 16:20 UTC, sfwn requested changes

2021-04-13 16:20 UTC, sfwn commented on modules/openapi/conf/conf.go
> +			return v, nil
please add unit test for this function.

2021-04-14 02:13 UTC, QvodSoldier commented on modules/openapi/conf/conf.go
> +			return v, nil
it's has existed in config_test.go

2021-04-14 17:11 UTC, sfwn approved these changes

2021-04-14 17:11 UTC, merged