fix: gittar remove skipAuth
erda-project/erda pull request #1856
Opened 2021-09-14 07:53 UTC by littlejiancc

#### What type of this PR
/kind feature

#### What this PR does / why we need it:
fix: gittar remove skipAuth

#### Which issue(s) this PR fixes:
[【gittar】鉴权取消skipAuth](https://erda.cloud/erda/dop/projects/387/issues/all?id=222904&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=TASK)
- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      gittar remove skipAuth        |
| 🇨🇳 中文    |      取消skipAuth逻辑，使用协议来区分鉴权逻辑      |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-09-14 09:47 UTC, sfwn requested changes

2021-09-14 09:47 UTC, sfwn commented on modules/gittar/auth/auth.go
> +func isGitProtocolRequest(c *webcontext.Context) bool {
add unit test for this function.

2021-09-14 09:47 UTC, sfwn commented on modules/gittar/auth/auth.go
> +		//校验通过缓存5分钟结果
use english

2021-09-14 11:10 UTC, littlejiancc commented on modules/gittar/auth/auth.go
> +		//校验通过缓存5分钟结果
done

2021-09-15 01:45 UTC, littlejiancc commented on modules/gittar/auth/auth.go
> +func isGitProtocolRequest(c *webcontext.Context) bool {
done

2021-09-15 01:55 UTC, sfwn approved these changes

2021-09-15 01:56 UTC, sfwn commented
/approve

2021-09-15 01:56 UTC, merged

2021-09-15 01:56 UTC, sfwn commented
/cherry-pick release/1.3

2021-09-15 02:03 UTC, littlejiancc commented
/cherry-pick release/1.3