feature: add pipeline and actionagent
erda-project/erda pull request #19
Opened 2021-03-22 06:38 UTC by sfwn

#### What type of PR is this?

feature

#### What this PR does / why we need it:

add pipeline & actionagent to erda

2021-03-22 06:40 UTC, Effet requested changes

2021-03-22 06:40 UTC, Effet commented on modules/actionagent/agenttool/tar.go
> +	"github.com/mholt/archiver"
bad order

2021-03-22 11:39 UTC, Muzry commented
/hold

2021-03-22 11:39 UTC, Muzry commented
/hold cancel

2021-03-22 11:46 UTC, sfwn commented on modules/actionagent/agenttool/tar.go
> +	"github.com/mholt/archiver"
adjusted.

2021-03-22 12:19 UTC, Muzry commented
/retest

2021-03-23 02:31 UTC, Effet approved these changes
a horrible huge PR!

2021-03-23 02:32 UTC, merged