autotest netportal set cookie to save login
erda-project/erda pull request #231
Opened 2021-04-22 12:51 UTC by kakj-go

#### What type of PR is this?
feature

#### What this PR does / why we need it:
add netportal cookie will not in request host domain the login will lost

2021-04-23 02:20 UTC, sfwn requested changes

2021-04-23 02:20 UTC, sfwn commented on pkg/apitestsv2/apitest.go
> +	"github.com/erda-project/erda/modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/cookiejar"
bad import.

2021-04-23 02:20 UTC, sfwn commented on pkg/apitestsv2/netportal.go
> +	"github.com/erda-project/erda/modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/cookiejar"
bad import.

2021-04-24 14:59 UTC, luoyuctl commented on pkg/apitestsv2/netportal.go
> +	"github.com/erda-project/erda/modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/cookiejar"
why indicate the same issue?

2021-04-26 06:50 UTC, sfwn approved these changes

2021-04-26 07:09 UTC, merged