user-workbench
erda-project/erda pull request #259
Opened 2021-04-27 02:58 UTC by chengjoey

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Specified Reivewers:
/assgin @your-reviewer

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation usage docs, etc.:

```docs

```

2021-04-27 03:08 UTC, sfwn requested changes

2021-04-27 03:08 UTC, sfwn commented on modules/cmdb/dao/application.go
> +// GetJoinedAppNumByUserId 获取用户在某个企业下的参与应用数
All new comments use English please.

2021-04-27 04:08 UTC, sfwn requested changes

2021-04-27 04:08 UTC, sfwn commented on bundle/workbench.go
> +	"github.com/erda-project/erda/apistructs"
adjust the import order.

2021-04-27 06:22 UTC, kakj-go commented on modules/cmdb/dao/application.go
> +	"fmt"
import

2021-04-27 06:22 UTC, kakj-go commented on modules/cmdb/dao/issue_state.go
> +func (client *DBClient) GetIssuesStatesByProjectIDList(projectIDS []uint64) ([]IssueState, error) {
projectIDS - > projectIDList

2021-04-27 06:22 UTC, kakj-go commented on modules/cmdb/dao/project.go
> +		Where(fmt.Sprintf("user_id = %s and org_id = %s and scope_type = \"%s\"", userID, orgID, apistructs.ProjectScopeType)).
sql injection risk, use ? not %s

2021-04-27 06:22 UTC, kakj-go commented on modules/cmdb/endpoints/endpoints.go
> +		{Path: "/api/orgs/{orgID}/nexus", Method: http.MethodGet , Handler: e.GetOrgNexus},
remove the spaces here

2021-04-27 06:22 UTC, kakj-go commented on modules/cmdb/endpoints/endpoints.go
> +		{Path: "/api/projects/actions/set-xproject-functions", Method: http.MethodPost, Handler: e.SetFunctions},
why change project to xproject

2021-04-27 06:22 UTC, kakj-go commented on modules/cmdb/endpoints/endpoints.go
> +		{Path: "/api/workbench/issues/list", Method: http.MethodGet, Handler: e.GetIssuesForWorkbench},
/api/workbench/issues/list -> /api/workbench/issues/actions/list

2021-04-28 06:19 UTC, sfwn requested changes

2021-04-28 06:19 UTC, sfwn commented on modules/cmdb/endpoints/endpoints.go
> +		//工作台相关
english

2021-04-28 06:19 UTC, sfwn commented on modules/cmdb/endpoints/workbench.go
> +	// 鉴权
same

2021-04-28 06:19 UTC, sfwn commented on modules/cmdb/services/issue/issue.go
> +	// 该项目下全部的state信息，之后不再查询state  key: stateID value:state
same

2021-04-28 07:42 UTC, sfwn approved these changes

2021-04-28 07:43 UTC, merged