Auto test space archive status feature, space list support sort, filter by name, status
erda-project/erda pull request #2758
Opened 2021-11-01 13:02 UTC by shuofan

#### What type of this PR
feature

#### What this PR does / why we need it:
Auto test space archive status feature, space list support sort, filter by name, status

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @sfwn @Effet 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |              |
| 🇨🇳 中文    |              |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-11-02 03:07 UTC, sfwn requested changes

2021-11-08 08:02 UTC, shuofan commented on .erda/migrations/qa/20211029-auto-test-space-archive-status.sql
> +ALTER TABLE `dice_autotest_space` ADD `archive_status` varchar(191) NOT NULL DEFAULT 'init' COMMENT 'auto test space archive status';
done

2021-11-08 08:02 UTC, shuofan commented on modules/dop/dao/autotest_space.go
> +	offset := (req.PageNo - 1) * req.PageSize
done

2021-11-08 09:58 UTC, sfwn requested changes

2021-11-08 09:58 UTC, sfwn commented on apistructs/autotest_space.go
> +	TestSpaceInit       AutoTestSpaceArchiveStatus = "autoTestSpaceInit"
simplify status in db.

2021-11-08 09:58 UTC, sfwn commented
Just merge into master, no need to release/1.4.

2021-11-09 09:38 UTC, sfwn approved these changes

2021-11-09 09:40 UTC, sfwn commented
/approve

2021-11-09 09:40 UTC, merged

2021-11-09 09:40 UTC, sfwn commented
/cherry-pick release/1.4