task policy
erda-project/erda pull request #2989
Opened 2021-11-10 05:42 UTC by kakj-go

#### What type of this PR

/kind feature

#### What this PR does / why we need it:
The pipeline task execution strategy is added. The new strategy can make the task no longer execute but directly fetch the latest successful result. This function can be used in automated testing, and users can save time to execute the same set of scenarios

#### Which issue(s) this PR fixes:

- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=228823&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTYsNDQwOF0sImFzc2lnbmVlSURzIjpbIjEwMDA1NjAiXSwiZmluaXNoZWRBdFN0YXJ0RW5kIjpbMTYzNjEyODAwMDAwMCxudWxsXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      The task of the pipeline increases the configuration of the execution strategy        |
| 🇨🇳 中文    |       流水线的任务增加执行策略的配置       |

#### Need cherry-pick to release versions?

/cherry-pick release/1.4

2021-11-16 03:18 UTC, sfwn requested changes

2021-11-16 03:18 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/policy.go
> +var policyHandlers = map[apistructs.PolicyName]func(*spec.PipelineTask, PolicyHandlerOptions) (*spec.PipelineTask, error){
abstract a interface for handler.

2021-11-16 03:18 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/policy.go
> +	return task, nil
Add TODO

2021-11-16 03:18 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/policy.go
> +		Sources:        []apistructs.PipelineSource{source},
Do you need add snippet-config labels to query?

2021-11-16 03:18 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/policy.go
> +		Sources:        []apistructs.PipelineSource{source},
And I think this method is too huge for this situation.
Maybe you should add a new db method.

2021-11-16 03:18 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/policy.go
> +	task.Status = beforeSuccessTask.Status
You should add a flag to distinguish this task's policy detail.

2021-11-16 03:18 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/policy.go
> +	tasks, err := opt.dbClient.ListPipelineTasksBySnippetPipelineID(&[]uint64{pipeline.ID}[0])
In logic, one snippet pipeline id should only bind to a certain parent task.

2021-11-16 03:18 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/policy.go
> +	tasks, err := opt.dbClient.ListPipelineTasksBySnippetPipelineID(&[]uint64{pipeline.ID}[0])
you should get parent task id from `pipeline_bases`.`parent_task_id`.

2021-11-16 03:18 UTC, sfwn commented on modules/pipeline/dbclient/op_pipeline_task.go
> +func (client *Client) ListPipelineTasksBySnippetPipelineID(snippetPipelineID *uint64, ops ...SessionOption) ([]spec.PipelineTask, error) {
No need this db function.

2021-11-16 03:18 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/policy.go
> +func (r *Reconciler) adaptorPolicy(task *spec.PipelineTask) (result *spec.PipelineTask, err error) {
use verb. `adaptPolicy`

2021-11-17 02:13 UTC, sfwn requested changes

2021-11-17 02:13 UTC, sfwn commented on apistructs/pipeline_yml.go
> +type PolicyName string
PolicyType

2021-11-17 02:13 UTC, sfwn commented on apistructs/pipeline_yml.go
> +	TryLastSuccessResultPolicyType PolicyName = "try-latest-success-result"
TryLatest

2021-11-17 02:13 UTC, sfwn commented on modules/pipeline/dbclient/op_pipeline_task.go
> -
no need

2021-11-17 02:40 UTC, kakj-go commented on modules/pipeline/pipengine/reconciler/policy.go
> +		DescCols:       []string{apistructs.PipelinePageListRequestIdColumn},
The effect of order by id is the same, and the query speed is faster

2021-11-17 03:52 UTC, sfwn approved these changes

2021-11-17 03:52 UTC, sfwn commented
/approve

2021-11-17 03:53 UTC, merged