Add error info in test file record, available when task failed
erda-project/erda pull request #3006
Opened 2021-11-10 12:37 UTC by shuofan

#### What type of this PR
feature

#### What this PR does / why we need it:
Add error info in test file record, available when task failed

#### Which issue(s) this PR fixes:

- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/ticket?assignee[]=1001073&id=244123&pageNo=1)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |              |
| 🇨🇳 中文    |              |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-11-12 07:30 UTC, sfwn requested changes

2021-11-12 07:30 UTC, sfwn commented on modules/dop/services/testcase/file_records.go
> +		r.ErrorInfo = fmt.Sprint(req.ErrorInfo)
judge error length.

2021-11-18 03:16 UTC, shuofan commented on modules/dop/services/testcase/file_records.go
> +		r.ErrorInfo = fmt.Sprint(req.ErrorInfo)
done

2021-11-24 02:24 UTC, sfwn approved these changes

2021-11-24 02:24 UTC, sfwn commented
/approve

2021-11-24 02:24 UTC, merged