ecs total number bugfix
erda-project/erda pull request #301
Opened 2021-05-08 07:37 UTC by WeiXuSeu

#### What type of this PR

Add one of the following kinds:
/kind bugfix

#### What this PR does / why we need it:
cloud resource get wrong ecs total number

#### Which issue(s) this PR fixes:
bugfix cloud resource ecs total number

#### Specified Reivewers:
/assgin @luobily

2021-05-10 06:57 UTC, luobily requested changes

2021-05-10 06:57 UTC, luobily commented on modules/ops/impl/aliyun-resources/ecs/ecs.go
> +		MAX := 1000
MAX should not be capitalized.

2021-05-10 06:57 UTC, luobily commented on modules/ops/impl/aliyun-resources/ecs/ecs.go
> +func Total(ctx aliyun_resources.Context, regions []string, cluster string) (int, error) {
Total() is too general

2021-05-10 06:57 UTC, luobily commented on modules/ops/impl/aliyun-resources/ecs/ecs.go
> +func Total(ctx aliyun_resources.Context, regions []string, cluster string) (int, error) {
capitalized?

2021-05-13 13:41 UTC, WeiXuSeu commented on modules/ops/impl/aliyun-resources/ecs/ecs.go
> +		MAX := 1000
OK，have modified

2021-05-13 13:41 UTC, WeiXuSeu commented on modules/ops/impl/aliyun-resources/ecs/ecs.go
> +func Total(ctx aliyun_resources.Context, regions []string, cluster string) (int, error) {
OK，have modified

2021-05-14 05:54 UTC, luobily approved these changes
lgtm

2021-05-17 02:07 UTC, luobily approved these changes
lgtm

2021-05-17 08:11 UTC, merged