split the result filed to metadata and inspect
erda-project/erda pull request #3043
Opened 2021-11-12 11:01 UTC by chengjoey

#### What type of this PR

Add one of the following kinds:
/kind bugfix

#### What this PR does / why we need it:
split the result filed to metadata and inspect, update metadata only when task callback

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=209158&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-11-15 06:21 UTC, chengjoey commented
![image](https://user-images.githubusercontent.com/30427474/141732152-932ae35c-20b4-42d6-9777-313b88d11aba.png)

convert to pipeline task dto:
![image](https://user-images.githubusercontent.com/30427474/141732324-75cdde45-79d5-4fb7-967d-bc83134fd7a6.png)

2021-11-18 05:54 UTC, sfwn requested changes

2021-11-18 05:54 UTC, sfwn commented on .erda/migrations/pipeline/20211112-pipeline-task-metadata-inspect.sql
> +ALTER TABLE `pipeline_tasks` ADD COLUMN `inspect` text COMMENT 'task的调度信息' AFTER `result`;
mediumtext

2021-11-18 05:54 UTC, sfwn commented on apistructs/pipeline_task.go
>  	Errors      []*PipelineTaskErrResponse `json:"errors,omitempty"`
use embed struct

2021-11-18 05:54 UTC, sfwn commented on apistructs/pipeline_task.go
> +func (t *PipelineTaskInspect) AppendError(newResponses ...*PipelineTaskErrResponse) []*PipelineTaskErrResponse {
use result is still ok

2021-11-18 05:54 UTC, sfwn commented on modules/pipeline/pipengine/actionexecutor/plugins/apitest/apitest.go
> +			meta = (*latestTask.Result).Metadata
add a function for spec.task to get metadata.
judge `nil` each time is bad.

2021-11-22 11:10 UTC, sfwn approved these changes

2021-11-22 11:10 UTC, merged