fix the bug of concurrent create snippet pipelines
erda-project/erda pull request #3126
Opened 2021-11-22 11:39 UTC by littlejiancc

#### What type of this PR
/kind bugfix

#### What this PR does / why we need it:
fix the bug of concurrent create snippet pipelines

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=252139&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |              |
| 🇨🇳 中文    |              |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-11-22 12:40 UTC, sfwn requested changes

2021-11-22 12:40 UTC, sfwn commented on modules/pipeline/services/pipelinesvc/snippet.go
> +	labels := make(map[string]string)
add comment for it.

2021-11-22 12:41 UTC, sfwn requested changes

2021-11-22 12:41 UTC, sfwn commented on modules/pipeline/services/pipelinesvc/snippet.go
> +	labels := make(map[string]string)
init size.

2021-11-22 12:44 UTC, littlejiancc commented on modules/pipeline/services/pipelinesvc/snippet.go
> +	labels := make(map[string]string)
done

2021-11-22 12:44 UTC, littlejiancc commented on modules/pipeline/services/pipelinesvc/snippet.go
> +	labels := make(map[string]string)
done

2021-11-23 02:18 UTC, sfwn approved these changes

2021-11-23 02:18 UTC, merged

2021-11-23 02:44 UTC, littlejiancc commented
/cherry-pick release/1.5-alpha1