register pipeline queues endpoints to openapi
erda-project/erda pull request #3211
Opened 2021-11-29 11:30 UTC by chengjoey

#### What type of this PR

Add one of the following kinds:
/kind feature

#### What this PR does / why we need it:
register pipeline queues endpoints to openapi

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=257961&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | Support pipeline queues endpoints in openapi              |
| 🇨🇳 中文    | 将pipeline队列接口注册到openAPI             |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-11-30 03:07 UTC, sfwn requested changes

2021-11-30 03:07 UTC, sfwn commented on modules/openapi/api/apis/pipeline/pipeline_queue_create.go
> +	Doc:          "summary: 创建pipeline队列",
add space between words.

2021-11-30 03:07 UTC, sfwn commented on modules/openapi/api/apis/pipeline/pipeline_queue_create.go
> +	CheckLogin:   true,
no need check login.

2021-11-30 03:32 UTC, chengjoey commented on modules/openapi/api/apis/pipeline/pipeline_queue_create.go
> +	Doc:          "summary: 创建pipeline队列",
adjusted

2021-12-01 06:04 UTC, sfwn approved these changes

2021-12-01 06:04 UTC, sfwn commented
/approve

2021-12-01 06:04 UTC, merged