limit task retry when system error
erda-project/erda pull request #3340
Opened 2021-12-10 10:45 UTC by chengjoey

#### What type of this PR

Add one of the following kinds:
/kind bugfix

#### What this PR does / why we need it:
limit task retry when system error

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=240758&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=772&type=BUG)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-12-10 10:46 UTC, chengjoey commented
![image](https://user-images.githubusercontent.com/30427474/145561851-1086c614-0bf9-4bd6-9a12-cf1d3063781f.png)
![image](https://user-images.githubusercontent.com/30427474/145561869-9d95f7b1-ccca-442b-b1b9-4572910d39cb.png)

2021-12-13 09:12 UTC, sfwn requested changes

2021-12-13 09:12 UTC, sfwn commented on apistructs/pipeline_task.go
> +	PipelineTaskMaxRetryLimit    = 100
How much time will the normal result of 100 retry times cost?
Please compare to 24hours.

2021-12-13 09:12 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/task.go
> +					rlog.TErrorf(tr.P.ID, tr.Task.ID, "failed to handle taskOp: %s, errors exceed limit, stop retry", taskOp.Op())
log add concrete limit number.

2021-12-16 11:08 UTC, sfwn approved these changes

2021-12-16 11:08 UTC, sfwn commented
/approve

2021-12-16 11:08 UTC, merged