jump over empty addon
erda-project/erda pull request #3351
Opened 2021-12-13 07:25 UTC by chengjoey

#### What type of this PR

Add one of the following kinds:
/kind bugfix

#### What this PR does / why we need it:
jump over nil addon field

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=263634&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  Fix the bug that jump over empty addon            |
| 🇨🇳 中文    |   修复了orchestrator遇到空的addon配置panic的问题           |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-12-14 09:34 UTC, Effet requested changes

2021-12-14 09:34 UTC, Effet commented on modules/orchestrator/services/deployment/deployment_context_test.go
> +
empty string?

2021-12-14 12:09 UTC, chengjoey commented on modules/orchestrator/services/deployment/deployment_context_test.go
> +
adjusted

2021-12-17 03:20 UTC, Effet approved these changes

2021-12-17 03:21 UTC, merged