Requirement process is based on inclusion relation stats
erda-project/erda pull request #3360
Opened 2021-12-14 02:17 UTC by shuofan

#### What type of this PR
feature

#### What this PR does / why we need it:
Requirement process is based on inclusion relation stats

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |              |
| 🇨🇳 中文    |              |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-12-14 09:48 UTC, sfwn requested changes

2021-12-14 09:48 UTC, sfwn commented on modules/dop/dao/issue_issue_relation.go
> +	sql := client.Debug().Table("dice_issue_relation").Where("issue_id in (?)", issueIDs)
set debug level globally, not here.

2021-12-14 10:28 UTC, shuofan commented on modules/dop/dao/issue_issue_relation.go
> +	sql := client.Debug().Table("dice_issue_relation").Where("issue_id in (?)", issueIDs)
done

2021-12-15 02:38 UTC, sfwn approved these changes

2021-12-15 02:38 UTC, sfwn commented
/approve

2021-12-15 02:38 UTC, merged