check data version when accept from executor done chan
erda-project/erda pull request #3402
Opened 2021-12-17 07:25 UTC by chengjoey

#### What type of this PR

Add one of the following kinds:
/kind bugfix

#### What this PR does / why we need it:
check data version when accept from executor done chan

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=264469&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  Fix the bug that get outputs error from pre-task            |
| 🇨🇳 中文    |  修复了无法从前面loop类型的task获取出参            |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-12-17 09:16 UTC, chengjoey commented
tested in terminus-test
![image](https://user-images.githubusercontent.com/30427474/146519764-70ea9f1c-d88a-400c-b6c4-61712759c543.png)
![image](https://user-images.githubusercontent.com/30427474/146519832-efc97b3f-a9d5-4977-b16e-5c80b0967dae.png)
all this task loop reports have result:
![image](https://user-images.githubusercontent.com/30427474/146519997-cb1a43a6-8d59-4d53-9e1d-dab6462ce774.png)
![image](https://user-images.githubusercontent.com/30427474/146520009-5f6681ee-d9f1-4108-bd9e-1036a820be0e.png)

2021-12-21 08:24 UTC, sfwn requested changes
Adjust all related var names.

2021-12-21 08:24 UTC, sfwn commented on modules/pipeline/spec/pipeline_task.go
> +func (pt *PipelineTask) GenerateExecutorVersion() string {
What is executor version? No, executor doesn't have version.
You should use `GenerateExecutorDoneChanDataVersion`.

2021-12-21 08:24 UTC, sfwn commented on modules/pipeline/spec/pipeline_task.go
> +func (pt *PipelineTask) CheckExecutorVersion(actualVersion string) error {
Same.

2021-12-21 09:09 UTC, sfwn requested changes

2021-12-21 09:09 UTC, sfwn commented on modules/pipeline/pipengine/actionexecutor/plugins/apitest/apitest.go
> +		executorVersion := task.GenerateExecutorDoneChanDataVersion()
xxx

2021-12-21 09:09 UTC, sfwn commented on modules/pipeline/spec/pipeline_task.go
> +type ExecutorChanData struct {
ExecutorDoneChanData

2021-12-21 09:09 UTC, sfwn commented on modules/pipeline/pipengine/actionexecutor/plugins/apitest/apitest.go
> +		executorVersion := task.GenerateExecutorDoneChanDataVersion()
doneChanDataVersion

2021-12-21 10:14 UTC, sfwn approved these changes

2021-12-21 10:14 UTC, sfwn commented
/approve

2021-12-21 10:15 UTC, merged

2021-12-21 10:56 UTC, Effet commented
/cherry-pick release/1.5