check if an addon that is not a platform exists when the project is deleted
erda-project/erda pull request #3419
Opened 2021-12-20 08:41 UTC by littlejiancc

#### What type of this PR

Add one of the following kinds:
/kind polish

#### What this PR does / why we need it:
check if an addon that is not a platform exists when the project is deleted

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=209165&iterationID=772&pId=0&type=BUG)

#### Specified Reviewers:

/assign @Effet 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |              |
| 🇨🇳 中文    |              |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-12-20 09:27 UTC, Effet requested changes

2021-12-20 09:27 UTC, Effet commented on modules/core-services/services/project/project.go
> +	})) > 0 {
should add some comment

2021-12-21 02:16 UTC, littlejiancc commented on modules/core-services/services/project/project.go
> +	})) > 0 {
done

2021-12-22 03:40 UTC, Effet approved these changes

2021-12-22 03:40 UTC, merged

2021-12-22 08:54 UTC, littlejiancc commented
/cherry-pick release/1.5