Automated testing speeds up global configuration queries
erda-project/erda pull request #3452
Opened 2021-12-22 09:21 UTC by kakj-go

#### What type of this PR

/kind feature

#### What this PR does / why we need it:
Since the query automation test configuration is a circular query, too many configurations will slow down the automation test componentization, which will seriously affect users' use

#### Which issue(s) this PR fixes:

- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=258176&iterationID=772&pId=0&type=BUG)
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODEsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=258180&iterationID=772&pId=0&type=BUG)

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       Optimizing query speed for global configuration       |
| 🇨🇳 中文    |      优化全局配置查询速度        |

2021-12-27 04:14 UTC, sfwn requested changes

2021-12-27 04:14 UTC, sfwn commented on modules/dop/services/autotest/global_config.go
> -		cfg, err := svc.parseGlobalConfigFromCmsNs(ns.Ns)
you have to reuse the logic of `parseGlobalConfigFromCmsNs`.

2021-12-27 04:14 UTC, sfwn commented on modules/dop/services/autotest/global_config.go
> +		result := apistructs.AutoTestGlobalConfig{Ns: ns}
too bad to copy these code again.

2021-12-27 04:14 UTC, sfwn commented on api/proto/core/pipeline/cms/cms.proto
> +  uint64 ID = 5 [json_name = "id"];
no id needed. `ns` is enough.

2021-12-27 04:14 UTC, sfwn commented on modules/pipeline/providers/cms/cms.service.go
> +	sortResult(results)
no need sort at pipeline level, just return with input order.

Or all use two-layer map, source for first-layer and ns for second-layer.

2021-12-27 04:14 UTC, sfwn commented on modules/pipeline/providers/cms/db/op.go
> +func (client *Client) BatchGetCmsNs(pipelineSource []string, ns []string, ops ...mysqlxorm.SessionOption) ([]PipelineCmsNs, error) {
use Plural forms of words.

2021-12-27 09:32 UTC, sfwn requested changes

2021-12-27 09:32 UTC, sfwn commented on api/proto/core/pipeline/cms/cms.proto
> +    repeated CmsNsConfigsGetRequest arrays = 1;
Can you query cms configs cross ns?

2021-12-27 09:32 UTC, sfwn commented on modules/pipeline/providers/cms/db/op.go
> +	if err := session.In("pipeline_source", pipelineSource).In("ns", ns).Find(&namespaces); err != nil {
You will get many unexpected result.
I think the size of source can only be one.

2021-12-28 06:16 UTC, sfwn requested changes

2021-12-28 06:16 UTC, sfwn commented on modules/pipeline/providers/cms/db/op.go
> +func (client *Client) BatchGetCmsNamespaces(pipelineSource string, ns []string, ops ...mysqlxorm.SessionOption) ([]PipelineCmsNs, error) {
namespaces

2021-12-28 06:16 UTC, sfwn commented on modules/pipeline/providers/cms/pipeline_cms.go
> +	var ns []string
namespaces

2021-12-28 06:16 UTC, sfwn commented on modules/pipeline/providers/cms/pipeline_cms.go
> +		getReq, ok := sourceKeyMap[relationNs.PipelineSource.String()+"_"+relationNs.Ns]
strange map

2021-12-28 06:16 UTC, sfwn commented on modules/pipeline/providers/cms/pipeline_cms.go
> +		var newConfig = pb.PipelineCmsConfig{
you should reuse the logic of config decode.

2021-12-28 10:55 UTC, sfwn requested changes

2021-12-28 10:55 UTC, sfwn commented on api/proto/core/pipeline/cms/cms.proto
> +  PipelineCmsNs pipelineCmsNs = 10;
just `ns`.

2021-12-28 10:55 UTC, sfwn commented on api/proto/core/pipeline/cms/cms.proto
> +      get: "/api/pipelines/cms/ns/action/batch-get-config",
/api/pipelines/cms/actions/batch-get-configs

2021-12-28 10:55 UTC, sfwn commented on api/proto/core/pipeline/cms/cms.proto
> +  repeated PipelineCmsConfig arrays = 1;
configs

2021-12-28 10:55 UTC, sfwn commented on modules/pipeline/providers/cms/db/op.go
> +func (client *Client) BatchGetCmsNsConfigs(cmsNsID []uint64, ops ...mysqlxorm.SessionOption) ([]PipelineCmsConfig, error) {
cmsNsIDs

2021-12-28 10:55 UTC, sfwn commented
And add test screenshot for this.

2021-12-28 11:10 UTC, kakj-go commented
> And add test screenshot for this.
CICD:

![image](https://user-images.githubusercontent.com/28723047/147560096-12f1aab7-a24c-48f5-9046-f3084d754200.png)

![image](https://user-images.githubusercontent.com/28723047/147560125-ea86b4a9-0274-44a7-8fc5-c4982311df38.png)

![image](https://user-images.githubusercontent.com/28723047/147560150-821f66d6-213d-44d3-aec7-99a4f464de75.png)

AUTOTEST:

![image](https://user-images.githubusercontent.com/28723047/147560322-9c49d8e2-db7a-48b4-ba8c-eadf3a819c27.png)


![image](https://user-images.githubusercontent.com/28723047/147560268-2dfc325a-ea18-438c-abc8-fba2685d2bce.png)


![image](https://user-images.githubusercontent.com/28723047/147560238-99d52358-2baf-42b1-aca6-4e8ff29b7e50.png)

2021-12-28 12:04 UTC, sfwn approved these changes

2021-12-28 12:04 UTC, sfwn commented
/approve

2021-12-28 12:04 UTC, merged