add org tags to pipeline log
erda-project/erda pull request #3456
Opened 2021-12-22 09:42 UTC by littlejiancc

#### What type of this PR

Add one of the following kinds:
/kind polish

#### What this PR does / why we need it:
add org tags to pipeline log

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMTI2MSJdfQ%3D%3D&id=267283&iterationID=772&pId=0&type=REQUIREMENT)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |              |
| 🇨🇳 中文    |              |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-12-23 09:24 UTC, sfwn requested changes

2021-12-23 09:24 UTC, sfwn commented on modules/dop/services/autotest_v2/scene.go
> +	project, err := svc.bdl.GetProject(uint64(space.ProjectID))
Is this bundle simple enough?

2021-12-23 09:24 UTC, sfwn commented on modules/dop/services/autotest_v2/scene.go
> +	org, err := svc.bdl.GetOrg(project.OrgID)
and this.

2021-12-23 09:24 UTC, sfwn commented on modules/pipeline/pipengine/actionexecutor/plugins/apitest/logic/main.go
> +		WithField(FieldOrgName, task.Extra.Labels["DICE_ORG_NAME"]).
uppercase or lowercase ?

2021-12-23 09:24 UTC, sfwn commented on modules/pipeline/spec/pipeline_extra.go
> +	if extra.NormalLabels != nil {
get from filterLabels and normalLabels by order.
and adjust method to get org name.

2021-12-23 09:31 UTC, littlejiancc commented on modules/dop/services/autotest_v2/scene.go
> +	org, err := svc.bdl.GetOrg(project.OrgID)
yes

2021-12-23 10:53 UTC, littlejiancc commented on modules/dop/services/autotest_v2/scene.go
> +	project, err := svc.bdl.GetProject(uint64(space.ProjectID))
Without quota by default

2021-12-24 02:37 UTC, sfwn approved these changes

2021-12-24 02:38 UTC, sfwn commented
/approve

2021-12-24 02:49 UTC, merged