openapi auth2 moved to the core service and pipeline decouples openapi
erda-project/erda pull request #3534
Opened 2021-12-29 08:52 UTC by kakj-go

#### What type of this PR

/kind feature

#### What this PR does / why we need it:
In order to realize the pipeline as the underlying service to decouple the upper-layer services, the auth2 interface is moved to core-services, so that the pipeline calls core-service instead of openapi

#### Which issue(s) this PR fixes:

- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMDU2MCJdfQ%3D%3D&id=267051&iterationID=772&pId=267098&type=TASK)

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      openapi auth2 moved to the core service and pipeline decouples openapi        |
| 🇨🇳 中文    |     openapi auth2 移至 core-services，pipeline 解耦 openapi         |

2021-12-29 08:54 UTC, kakj-go commented
test image:

CICD:

![image](https://user-images.githubusercontent.com/28723047/147644265-1e3cddb1-25fc-4c8a-b56e-f3c5e3714bba.png)

![image](https://user-images.githubusercontent.com/28723047/147644356-0b4204b2-6e85-4c09-b57c-65d7a8914ed7.png)

2021-12-31 03:17 UTC, sfwn requested changes

2021-12-31 03:17 UTC, sfwn commented on bundle/token.go
> +func (b *Bundle) GetCoreServiceOAuth2Token(req apistructs.OpenapiOAuth2TokenGetRequest) (*apistructs.OpenapiOAuth2Token, error) {
reuse original bundle and just replace openapi to core-services.

2021-12-31 03:17 UTC, sfwn commented on bundle/token.go
> +func (b *Bundle) GetCoreServiceOAuth2Token(req apistructs.OpenapiOAuth2TokenGetRequest) (*apistructs.OpenapiOAuth2Token, error) {
and rename to GetOAuth2Token, remove module prefix

2022-01-04 02:33 UTC, sfwn requested changes

2022-01-04 02:33 UTC, sfwn commented on bundle/openapi.go
>  func (b *Bundle) GetOpenapiOAuth2Token(req apistructs.OpenapiOAuth2TokenGetRequest) (*apistructs.OpenapiOAuth2Token, error) {
no need this method anymore.
just rename to GetOAuth2Token, and adjust other related structs pls.

2022-01-04 02:33 UTC, sfwn commented on bundle/token.go
> +func (b *Bundle) GetOAuth2Token(req apistructs.OpenapiOAuth2TokenGetRequest) (*apistructs.OpenapiOAuth2Token, error) {
delete these two funcs.

2022-01-04 12:01 UTC, sfwn approved these changes

2022-01-07 01:54 UTC, sfwn approved these changes

2022-01-07 01:54 UTC, sfwn commented
/approve

2022-01-07 01:54 UTC, merged