fix: issue event get context by org locale
erda-project/erda pull request #3563
Opened 2021-12-30 08:44 UTC by chengjoey

#### What this PR does / why we need it:
issue event get context by org locale

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODNdLCJtZW1iZXIiOlsiMTAwMTIwNSJdfQ%3D%3D&id=206539&iterationID=772&pId=0&type=BUG)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  fix: issue event get context by org locale            |
| 🇨🇳 中文    |   事项发送内容中英文           |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2021-12-30 09:13 UTC, Effet requested changes

2021-12-30 09:13 UTC, Effet commented on modules/dop/services/issuestream/issue_stream.go
>  	logrus.Debugf("old issue content is: %s", content)
you should also move down this line

2021-12-31 01:40 UTC, chengjoey commented on modules/dop/services/issuestream/issue_stream.go
>  	logrus.Debugf("old issue content is: %s", content)
adjusted

2021-12-31 10:53 UTC, Effet approved these changes

2021-12-31 10:53 UTC, merged