fix: project pipeline Reduce status queries and create precheck
erda-project/erda pull request #3801
Opened 2022-01-18 14:41 UTC by kakj-go

#### What this PR does / why we need it:
bugfix project pipeline Reduce status queries
bugfix project pipeline create precheck same name definition

#### Which issue(s) this PR fixes:

- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=275799&iterationID=772&pId=0&type=BUG)

- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=276321&iterationID=772&pId=0&type=BUG)

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       project pipeline Reduce status queries and create precheck       |
| 🇨🇳 中文    |      项目管道减少状态查询并创建预检查        |

2022-01-19 05:34 UTC, Effet requested changes

2022-01-19 05:34 UTC, Effet commented on modules/dop/providers/projectpipeline/service_impl.go
> +		return false, err
optimize it, too slow

2022-01-19 10:00 UTC, Effet submitted a review, later dismissed

2022-01-19 10:00 UTC, Effet commented on modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/filterContainer/customFilter/provider.go
> +		}
separate a func like transferStatus

2022-01-20 11:03 UTC, sfwn approved these changes

2022-01-20 11:04 UTC, sfwn commented
/approve

2022-01-20 11:06 UTC, merged

2022-01-20 11:53 UTC, kakj-go commented
/cherry-pick release/1.6-alpha.2