feat: browser/service-transaction charts support dynamic Y unit
erda-project/erda pull request #3816
Opened 2022-01-19 10:58 UTC by snakorse

#### What this PR does / why we need it:

feature: browser/service-transaction charts support dynamic Y unit

#### Specified Reviewers:

/assign @liuhaoyang @innerpeacez 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |        feat: browser/service-transaction charts support dynamic Y unit      |
| 🇨🇳 中文    |       前端监控/服务调用 图表支持y轴动态单位       |

#### Need cherry-pick to release versions?

/cherry-pick release/1.6-alpha.2

2022-01-19 11:00 UTC, innerpeacez requested changes

2022-01-19 11:00 UTC, innerpeacez commented on modules/msp/apm/browser/components/browser-overview/charts/page_req_duration_distribution/provider.go
> +			WithYOptions(bubblegraph.NewOptionsBuilder().WithType(structure.Number).WithPrecision(structure.Millisecond).Build())
type is structure.Time

2022-01-20 03:26 UTC, innerpeacez submitted a review, later dismissed

2022-01-20 07:50 UTC, liuhaoyang approved these changes

2022-01-20 07:51 UTC, merged