fix update project error
erda-project/erda pull request #389
Opened 2021-05-19 11:24 UTC by QvodSoldier

#### What type of this PR

Add one of the following kinds:
/kind bug
/kind cleanup
/kind documentation
/kind feature
/kind design

#### What this PR does / why we need it:

Fix the problem that if the display name is empty, it will be overwritten by the name when updating the project

#### Which issue(s) this PR fixes:
[update project bug](https://erda-org.erda.cloud/workBench/projects/387/issues/all?id=60277&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=436&type=BUG)

#### Specified Reivewers:
/assgin @Effet

2021-05-20 01:48 UTC, sfwn requested changes

2021-05-20 01:48 UTC, sfwn commented on modules/cmdb/services/project/project.go
> +		logrus.Infof("failed to marshal clusterConfig, (%v)", err)
use correct log level of Errorf.

2021-05-20 01:48 UTC, sfwn commented on modules/cmdb/services/project/project.go
> +	// DEV/TEST/STAGING/PROD四个环境集群配置
All new comments use english please.

2021-05-20 01:48 UTC, sfwn commented on modules/cmdb/services/project/project.go
> +	// 空则不配置
same.

2021-05-21 02:01 UTC, QvodSoldier commented on modules/cmdb/services/project/project.go
> +		logrus.Infof("failed to marshal clusterConfig, (%v)", err)
Has been changed

2021-05-21 02:02 UTC, QvodSoldier commented on modules/cmdb/services/project/project.go
> +	// 空则不配置
Has been changed

2021-05-21 07:57 UTC, sfwn approved these changes

2021-05-21 07:57 UTC, merged