project pipeline create name and source pre check
erda-project/erda pull request #3936
Opened 2022-01-25 03:19 UTC by kakj-go

#### What this PR does / why we need it:
The project pipeline pre checks whether the name is unique under the project and whether the source is created repeatedly

#### Which issue(s) this PR fixes:

- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls4ODMsNzcyXSwibWVtYmVyIjpbIjEwMDA1NjAiXX0%3D&id=278270&iterationID=772&pId=0&type=TASK)

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |        Some interfaces for uniqueness verification of project pipeline      |
| 🇨🇳 中文    |        项目流水线一些唯一性校验的接口      |

2022-01-25 03:39 UTC, Effet requested changes

2022-01-25 03:39 UTC, Effet commented on modules/dop/providers/projectpipeline/provider.go
> +	APIMTrans i18n.Translator    `translator:"project-pipeline" required:"true"`
just `Trans`, not APIMTrans

2022-01-25 03:39 UTC, Effet commented on api/proto/dop/projectpipeline/projectpipeline.proto
> +  }
as a rpc to provide, I think you can combine these two apis to one API like:
`POST /api/project-pipeline/actions/check-create-param`

and the body:
```json
{
  "fields": [
    {
      "field": "name",
      "value": "my name",
    },
    {
      "field": "source",
      "value": "my source",
    }
  ]
}
```

2022-01-26 02:41 UTC, sfwn requested changes

2022-01-26 02:41 UTC, sfwn commented on modules/dop/providers/projectpipeline/service_impl.go
> +	orgDto, err := p.bundle.GetOrg(projectDto.OrgID)
bad performance.
you can add orgname to previous GetProject bundle.

2022-01-26 03:42 UTC, Effet approved these changes

2022-01-26 03:43 UTC, sfwn approved these changes

2022-01-26 03:44 UTC, sfwn commented
/approve

2022-01-26 03:44 UTC, merged