feat: Input filter merged into standard filter with outside property
erda-project/erda pull request #3994
Opened 2022-02-07 08:39 UTC by shuofan

#### What this PR does / why we need it:
Input filter merged into standard filter with outside property

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @Effet 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |    Input filter merged into standard filter with outside property          |
| 🇨🇳 中文    |    inputFilter 组件合并入标准 filter，支持 expose          |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-02-07 09:41 UTC, Effet requested changes

2022-02-07 09:41 UTC, Effet commented on modules/dop/component-protocol/components/project-runtime/list/list.go
> +	if nameFilterMap, ok := (*p.Sdk.GlobalState)["nameFilter"]; ok {
it's not a map

2022-02-07 10:02 UTC, shuofan commented on modules/dop/component-protocol/components/project-runtime/list/list.go
> +	if nameFilterMap, ok := (*p.Sdk.GlobalState)["nameFilter"]; ok {
done

2022-02-07 10:05 UTC, Effet approved these changes

2022-02-07 10:05 UTC, Effet commented
/approve

2022-02-08 13:14 UTC, Effet approved these changes

2022-02-08 13:14 UTC, merged