feat: Standard filter in issue manage
erda-project/erda pull request #4009
Opened 2022-02-10 06:40 UTC by shuofan

#### What this PR does / why we need it:
Standard filter in issue manage

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  Standard filter in issue manage            |
| 🇨🇳 中文    |   事项列表 标准筛选器           |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-02-10 07:36 UTC, sfwn requested changes

2022-02-10 07:36 UTC, sfwn commented on modules/dop/component-protocol/components/issue-manage/issueFilter/provider.go
> +	base.InitProviderWithCreator("issue-manage", "issueFilter", func() servicehub.Provider { return &provider{} })
use cpregister.RegisterComponent

2022-02-10 09:25 UTC, shuofan commented on modules/dop/component-protocol/components/issue-manage/issueFilter/provider.go
> +	base.InitProviderWithCreator("issue-manage", "issueFilter", func() servicehub.Provider { return &provider{} })
done

2022-02-11 03:55 UTC, sfwn approved these changes

2022-02-11 03:58 UTC, sfwn commented
/approve

2022-02-11 03:58 UTC, merged