refactor(core-services): remove core-services dependency on gittar
erda-project/erda pull request #4075
Opened 2022-02-16 11:33 UTC by littlejiancc

#### What this PR does / why we need it:
remove core-services dependency on gittar

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOlsxMDkwXSwibWVtYmVyIjpbIjEwMDEyNjEiXX0%3D&id=279508&iterationID=1090&pId=267102&type=TASK)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |    remove core-services dependency on gittar          |
| 🇨🇳 中文    |    解除core-services依赖gittar          |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-02-21 08:33 UTC, sfwn requested changes

2022-02-21 08:33 UTC, sfwn commented on modules/core-services/services/application/appliation.go
> -	// 判断应用下是否有runtime，无 runtime 时应用可删除
What if the user calls core-services' to delete app with runtime directly?

2022-02-21 08:33 UTC, sfwn commented on apistructs/gittar.go
> +func MakeRepoPath(orgName, proName, appName string) string {
add a `gittarutil` pkg is better.

2022-02-22 02:01 UTC, littlejiancc commented on apistructs/gittar.go
> +func MakeRepoPath(orgName, proName, appName string) string {
done

2022-02-23 02:17 UTC, sfwn submitted a review, later dismissed

2022-02-23 03:00 UTC, sfwn commented
/approve

2022-02-23 03:00 UTC, merged