feat:kms support rsa 4096
erda-project/erda pull request #4080
Opened 2022-02-17 06:26 UTC by chengjoey

#### What this PR does / why we need it:
kms support rsa 4096

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOlsxMDkwXSwibWVtYmVyIjpbIjEwMDEyMDUiXX0%3D&id=282915&iterationID=1090&pId=0&type=TASK)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | Support kms rsa 409             |
| 🇨🇳 中文    |   kms的rsa           |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-02-17 09:23 UTC, sfwn commented
also support 2048/3072

2022-02-17 09:24 UTC, sfwn commented
add your test images.

2022-02-17 09:50 UTC, chengjoey commented
> add your test images.
1. create rsa key
![image](https://user-images.githubusercontent.com/30427474/154448877-bdc70e1a-5cad-4730-ae43-4a86af57600e.png)
 at the same time, will store the key info and version info
![image](https://user-images.githubusercontent.com/30427474/154449804-da652206-8ca5-4e27-abe6-da6f8801174b.png)

2. encrypt and decrypt:
![image](https://user-images.githubusercontent.com/30427474/154449935-2859f715-492c-4b7d-a90e-554ad32297eb.png)
![image](https://user-images.githubusercontent.com/30427474/154449976-0623361c-dcdf-4a58-8b98-389af1be961d.png)

3. rotate key version:
will add a new version in store and change key primary version
![image](https://user-images.githubusercontent.com/30427474/154450197-c34182ea-231e-4fd6-9889-a63074899499.png)

2022-02-17 10:57 UTC, chengjoey commented
> also support 2048/3072

added

2022-02-18 02:48 UTC, sfwn requested changes

2022-02-18 02:48 UTC, sfwn commented on pkg/kms/plugins/dicekms/kms.go
> +		rsaCrypt := encryption.NewRSAScrypt(encryption.RSASecret{
NewRSA Scrypt is strange

2022-02-18 03:04 UTC, sfwn commented
RSA has max data length limitation, so do you need check before encrypt? please test it.

2022-02-18 03:14 UTC, chengjoey commented
> RSA has max data length limitation, so do you need check before encrypt? please test it.
The standard library `crypto` will check the length of src, and return error : `message too long`
![image](https://user-images.githubusercontent.com/30427474/154610439-3b1df81a-5f97-4051-b183-432eeb282554.png)

2022-02-18 03:33 UTC, sfwn commented
how about cipher type?

2022-02-18 05:15 UTC, chengjoey commented
> how about cipher type?
CBC,CFB,OFB,ECB  ard different modes of aes encryption
![image](https://user-images.githubusercontent.com/30427474/154621927-134fe0f2-53a3-4629-85a1-8f064d0aceb3.png)

2022-02-18 07:18 UTC, sfwn requested changes

2022-02-18 07:18 UTC, sfwn commented on pkg/kms/kmscrypto/rsa_2048_4096.go
> +type RsaCrypt struct {
`RsaCrypt` `RSASceret`

2022-02-18 07:43 UTC, chengjoey commented on pkg/kms/kmscrypto/rsa_2048_4096.go
> +type RsaCrypt struct {
`RsaCrypt ` redefine as `RSACrypt`

2022-02-18 07:44 UTC, chengjoey commented on pkg/kms/kmscrypto/rsa_2048_4096.go
> +func DecodeString(data string, encodedType Encode) ([]byte, error) {
move these method `DecodeString` `EncodeToString` to util.go

2022-02-22 15:56 UTC, sfwn approved these changes

2022-02-22 15:56 UTC, merged