Fixed the problem that the scheduled task did not execute the compensation policy and could not get cronid from etcd
erda-project/erda pull request #4110
Opened 2022-02-21 11:05 UTC by kakj-go

#### What this PR does / why we need it:
Fixed the problem that the scheduled task did not execute the compensation policy and could not get cronid from etcd

#### Which issue(s) this PR fixes:

- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=283779&issueFilter__urlQuery=eyJhc3NpZ25lZUlEcyI6WyIxMDAxMjYxIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=TASK)

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       Fixed the problem that the scheduled task did not execute the compensation policy and could not get cronid from etcd       |
| 🇨🇳 中文    |       修复定时任务未执行补偿策略无法从 etcd 获取 cronid 的问题       |

2022-02-21 11:09 UTC, kakj-go commented
pipeline.yml
```yaml
version: "1.1"
cron: '*/1 * * * *'
cron_compensator:
  enable: true
  latest_first: false
  stop_if_latter_executed: false
stages:
  - stage:
      - custom-script:
          alias: custom-script
          description: 运行自定义命令
          version: "1.0"
          image: registry.erda.cloud/erda-actions/custom-script-action:1.0-20211216-b1d5635
          commands:
            - sleep 130
```

test image:

Cron newly created record is not executed

![image](https://user-images.githubusercontent.com/28723047/154943471-32113f62-a86d-432c-8b89-fb823c05f6c6.png)

Always follow the strategy
![image](https://user-images.githubusercontent.com/28723047/154943534-1d89d4ac-6f1f-4ad5-8b82-309ac9a02502.png)

log:

![image](https://user-images.githubusercontent.com/28723047/154943873-f893b00f-7b84-4aee-96be-55aec35f5112.png)

2022-02-21 11:18 UTC, sfwn requested changes

2022-02-21 11:20 UTC, sfwn requested changes

2022-02-21 11:20 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/cron_strategy_compensator.go
> +		logrus.Infof("[doCronCompensate]: can not get cronId %d err: %v", *pipelineWithTasks.Pipeline.CronID, err)
cronID: %d, err: %v

polish all others pls

2022-02-21 11:20 UTC, sfwn commented on modules/pipeline/pipengine/reconciler/cron_strategy_compensator.go
> +	notFind, err := r.js.Notfound(pCtx, fmt.Sprint(EtcdNeedCompensatePrefix, *pipelineWithTasks.Pipeline.CronID))
notFound

2022-02-22 03:44 UTC, sfwn approved these changes

2022-02-22 03:44 UTC, sfwn commented
/approve

2022-02-22 03:44 UTC, merged