fix(pipeline): disable eci for pipelines containing custom tasks
erda-project/erda pull request #4123
Opened 2022-02-22 09:56 UTC by chengjoey

#### What this PR does / why we need it:
disable eci for pipelines containing custom tasks

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMDkwLDExMTVdLCJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=285869&iterationID=1115&pId=0&type=TASK)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  Fix the bug that disable eci for pipelines containing custom tasks            |
| 🇨🇳 中文    |  禁止包含自定义任务的流水线使用eci            |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-02-22 12:02 UTC, sfwn requested changes

2022-02-23 06:19 UTC, chengjoey commented on modules/pipeline/pkg/container_provider/container_instance_provider.go
> +func ConstructContainerProviderByLabelAndStages(labels map[string]string, stages []*pipelineyml.Stage) *apistructs.ContainerInstanceProvider {
adjusted

2022-02-23 08:36 UTC, sfwn approved these changes

2022-02-23 08:36 UTC, sfwn commented
/approve

2022-02-23 08:36 UTC, merged