feat:Issue connection changed to unidirectional relation
erda-project/erda pull request #4330
Opened 2022-03-10 09:28 UTC by shuofan

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |              |
| 🇨🇳 中文    |              |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-03-11 08:12 UTC, Effet requested changes

2022-03-11 08:12 UTC, Effet commented on modules/dop/endpoints/issue_related.go
> +				return apierrors.ErrGetIssueRelations.InternalError(err).ToResp(), nil
I suggest to encapsulate a func

2022-03-11 09:08 UTC, shuofan commented on modules/dop/dao/issue_issue_relation.go
> +	if err := sql.Where("issue_id = ? and related_issue in (?) or issue_id in (?) and related_issue = ?", issueRelation.IssueID, relatedIssues, relatedIssues, issueRelation.IssueID).
sure

2022-03-11 09:35 UTC, shuofan commented on modules/dop/endpoints/issue_related.go
> +				return apierrors.ErrGetIssueRelations.InternalError(err).ToResp(), nil
done

2022-03-14 02:15 UTC, Effet requested changes

2022-03-14 02:15 UTC, Effet commented on modules/dop/dao/issue_issue_relation.go
> +		issueID, relatedIssueID, relatedIssueID, issueID)
also add some (, )

2022-03-14 02:50 UTC, shuofan commented on modules/dop/dao/issue_issue_relation.go
> +		issueID, relatedIssueID, relatedIssueID, issueID)
done

2022-03-14 02:50 UTC, Effet approved these changes

2022-03-14 02:51 UTC, Effet commented
/approve

2022-03-14 03:03 UTC, merged