feat(pipeline): Optimize pipeline db gc
erda-project/erda pull request #4416
Opened 2022-03-22 05:51 UTC by littlejiancc

#### What this PR does / why we need it:
Optimize pipeline db gc

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTQ2XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=295146&iterationID=1146&pId=290591&type=TASK)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      Optimize pipeline db gc        |
| 🇨🇳 中文    |       优化pipeline db gc       |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-03-22 07:15 UTC, sfwn requested changes

2022-03-22 07:15 UTC, sfwn commented on modules/pipeline/providers/dbgc/dbgc.go
> +			logrus.Errorf("failed to do gc logic, pipelineID: %d, err: %v", pipeline.PipelineID, err)
use p.Log

2022-03-22 07:17 UTC, sfwn commented
it's not graceful: modules/pipeline/providers/dbgc/dbgc.go:44

2022-03-22 07:17 UTC, sfwn commented
make modules/pipeline/providers/dbgc/dbgc.go:50 configurable, and others.

2022-03-23 09:14 UTC, littlejiancc commented on modules/pipeline/providers/dbgc/dbgc.go
> +			logrus.Errorf("failed to do gc logic, pipelineID: %d, err: %v", pipeline.PipelineID, err)
done

2022-03-23 09:17 UTC, sfwn requested changes

2022-03-23 09:17 UTC, sfwn commented on modules/pipeline/conf/conf.go
> +	PipelineDBGCCron       string        `env:"PIPELINE_DBGC_CRON" default:"0 0 0/2 * * ?"`
move to provider self config.

2022-03-23 11:09 UTC, sfwn approved these changes

2022-03-23 11:09 UTC, sfwn commented
/approve

2022-03-23 11:27 UTC, merged