fix: Update approval url in notify message
erda-project/erda pull request #4501
Opened 2022-03-29 07:05 UTC by shuofan

#### What this PR does / why we need it:
Update approval url in notify message

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0LDExNzgsMTEzMV0sImFzc2lnbmVlIjpbIjEwMDEwNzMiXX0%3D&id=298014&iterationID=1164&pId=0&type=BUG)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |    Update approval url in notify message          |
| 🇨🇳 中文    |  更新通知中的审批链接             |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-03-29 09:39 UTC, sfwn requested changes

2022-03-29 09:39 UTC, sfwn commented on modules/core-services/services/approve/approve.go
> -	url := fmt.Sprintf("%s://%s-org.%s/%s/orgCenter/approval/%s?id=%d",
erda.cloud/{org}/orgCenter/approval

2022-03-30 05:55 UTC, shuofan commented on modules/core-services/services/approve/approve.go
> -	url := fmt.Sprintf("%s://%s-org.%s/%s/orgCenter/approval/%s?id=%d",
done

2022-03-30 07:22 UTC, sfwn approved these changes

2022-03-30 07:22 UTC, sfwn commented
/approve

2022-03-30 07:22 UTC, merged