DOP adds batch update CMS API
erda-project/erda pull request #4503
Opened 2022-03-29 07:57 UTC by kakj-go

#### What this PR does / why we need it:
The project level pipeline adds global parameter configuration and lacks update interface

#### Which issue(s) this PR fixes:

- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0XSwiYXNzaWduZWUiOlsiMTAwMDU2MCJdfQ%3D%3D&id=299271&iterationID=1164&pId=293275&type=TASK)

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       DOP adds batch update CMS API       |
| 🇨🇳 中文    |      DOP添加批量更新CMS API        |

2022-03-29 10:58 UTC, sfwn requested changes

2022-03-29 10:58 UTC, sfwn commented on modules/openapi/api/apis/dop/adaptor_cicd_config_del.go
> -	Audit: func(ctx *spec.AuditContext) error {
how to do audit in your new code?

2022-03-30 02:33 UTC, kakj-go commented
audit image:

![image](https://user-images.githubusercontent.com/28723047/160739238-d0a75210-a9b1-471e-83ed-c34146e6ece2.png)

2022-03-30 03:07 UTC, sfwn requested changes

2022-03-30 03:07 UTC, sfwn commented on api/proto/dop/cms/cicdcms.proto
> +
remove useless blank lines.

2022-03-30 03:07 UTC, sfwn commented on modules/dop/providers/cms/cicdcmsservice.go
> +	return &pb.CICDCmsCreateResponse{
do you need add audit for create?

2022-03-30 03:08 UTC, sfwn commented
> audit image:
> 
> ![image](https://user-images.githubusercontent.com/28723047/160739238-d0a75210-a9b1-471e-83ed-c34146e6ece2.png)

删除了流水线配置
设置了流水线配置

2022-03-30 06:07 UTC, sfwn approved these changes

2022-03-30 06:07 UTC, sfwn commented
/approve

2022-03-30 06:09 UTC, merged