feat(dop): Project pipeline supports editing sources
erda-project/erda pull request #4609
Opened 2022-04-13 11:45 UTC by littlejiancc

#### What this PR does / why we need it:
Project pipeline supports editing sources

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc0XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=304808&iterationID=1174&pId=301486&type=TASK)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |   Project pipeline supports editing sources           |
| 🇨🇳 中文    |     项目流水线支持编辑源         |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-04-15 07:45 UTC, Effet requested changes

2022-04-15 07:45 UTC, Effet commented on api/proto/dop/projectpipeline/projectpipeline.proto
> +  string fileName = 8 [(validator.field) = {string_not_empty: true}];
I suggest to separate a new api for source update only.

2022-04-15 07:45 UTC, Effet commented on modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
> +				}
separate a new func, add test

2022-04-15 08:51 UTC, littlejiancc commented on modules/dop/component-protocol/components/project-pipeline/myPage/tabsTable/pipelineTable/provider.go
> +				}
done

2022-04-18 02:36 UTC, Effet approved these changes

2022-04-18 02:39 UTC, merged