fix(dop,pipeline): fix autotest can not set Content-Type header and can not get result that not a json
erda-project/erda pull request #4671
Opened 2022-04-21 06:36 UTC by kakj-go

#### What this PR does / why we need it:
1. Fix that the automated test could not customize the content type header
2. Fix that the automated test cannot get a result that is not JSON

#### Which issue(s) this PR fixes:

- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTc4LDExOTAsMTIxOCwxMTc0XSwiYXNzaWduZWUiOlsiMTAwMDU2MCJdfQ%3D%3D&id=306533&iterationID=1174&pId=0&type=BUG)

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       fix autotest can not set Content-Type header，and can not get result that not a json        |
| 🇨🇳 中文    |      修复自动测试无法设置 Content-Type header，和无法得到非 json 的结果        |

2022-04-21 09:43 UTC, sfwn requested changes

2022-04-21 09:43 UTC, sfwn commented on pkg/encoding/jsonparse/parse.go
> +		if express == "." || express == "" {
I think `.` is required.

2022-04-22 01:53 UTC, kakj-go commented on pkg/apitestsv2/apitest.go
> +	// headers
The header priority set by the user should be higher than that set by the code 187 guild

2022-04-22 02:03 UTC, sfwn approved these changes

2022-04-22 02:03 UTC, sfwn commented
/approve

2022-04-22 02:19 UTC, merged