feat(pipeline): Add edge cluster pipeline reporting
erda-project/erda pull request #4676
Opened 2022-04-21 08:13 UTC by littlejiancc

#### What this PR does / why we need it:
 Add edge cluster pipeline reporting

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTkwLDExNzRdLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=300219&iterationID=1190&pId=306714&type=TASK)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |    Add edge cluster pipeline reporting          |
| 🇨🇳 中文    |     增加边缘集群流水线上报         |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-04-28 10:00 UTC, sfwn requested changes

2022-04-28 11:01 UTC, littlejiancc commented on modules/pipeline/providers/edgereporter/provider.go
> +	edgeRegister edgepipeline_register.Interface
done

2022-04-28 11:01 UTC, littlejiancc commented on modules/pipeline/providers/edgereporter/provider.go
> +	CompensatorDuration time.Duration `file:"COMPENSATOR_DURATION" env:"COMPENSATOR_DURATION" default:"2h"`
done

2022-04-28 11:01 UTC, littlejiancc commented on modules/pipeline/providers/edgereporter/interface.go
> +	AddOneTaskReporter(taskID uint64)
done

2022-04-28 11:02 UTC, littlejiancc commented on modules/pipeline/dbclient/op_pipeline_task.go
> +func (client *Client) MultiCreatePipelineTasks(pts []spec.PipelineTask, ops ...SessionOption) (err error) {
done

2022-04-28 11:03 UTC, littlejiancc commented on modules/pipeline/dbclient/op_pipeline_stage.go
> +func (client *Client) MultiCreatePipelineStages(stages []spec.PipelineStage, ops ...SessionOption) (err error) {
done

2022-04-28 11:03 UTC, littlejiancc commented on apistructs/pipeline.go
> +	PipelineCallbackTypeOfTask     PipelineCallbackType = "TASK"
done

2022-04-29 02:19 UTC, sfwn commented on modules/pipeline/dbclient/op_pipeline_stage.go
> +	_, err = session.Table("pipeline_stages").InsertMulti(stages)
use spec's table name

2022-04-29 02:19 UTC, sfwn commented on modules/pipeline/dbclient/op_pipeline_task.go
> +	_, err = session.Table("pipeline_tasks").InsertMulti(&pts)
use spec's table name

2022-04-29 02:22 UTC, sfwn commented on modules/pipeline/providers/edgereporter/provider.go
> +	CompensatorDuration time.Duration `file:"COMPENSATOR_DURATION" env:"COMPENSATOR_DURATION" default:"2h"`
nothing changed

2022-04-29 02:46 UTC, littlejiancc commented on apistructs/pipeline.go
> +	PipelineCallbackTypeOfEdgeTaskReport     PipelineCallbackType = "TASK"
done

2022-04-29 02:46 UTC, littlejiancc commented on modules/pipeline/dbclient/op_pipeline_task.go
> +	_, err = session.Table("pipeline_tasks").InsertMulti(&pts)
done

2022-04-29 02:47 UTC, littlejiancc commented on modules/pipeline/dbclient/op_pipeline_stage.go
> +	_, err = session.Table("pipeline_stages").InsertMulti(stages)
done

2022-05-01 12:50 UTC, sfwn approved these changes

2022-05-01 12:50 UTC, sfwn commented
/approve

2022-05-01 12:50 UTC, merged