feat: Replace MySQL client implementation with MySQL provider
erda-project/erda pull request #4766
Opened 2022-04-29 09:00 UTC by sixther-dc

#### What this PR does / why we need it:
Replace MySQL client implementation with MySQL provider.
service directory rename to apps.

#### Which issue(s) this PR fixes:

#### Specified Reviewers:

/assign @luobily @skoo87 @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |     Replace MySQL client implementation with MySQL provider         |
| 🇨🇳 中文    |       MySQL client的实现改为 provider      |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-04-30 14:14 UTC, sfwn requested changes

2022-04-30 14:14 UTC, sfwn commented on modules/dop/endpoints/application_publish_item.go
> +	"github.com/erda-project/erda/modules/apps/admin/apierrors"
I believe this is a wrong import.

2022-04-30 14:14 UTC, sfwn commented on modules/dop/component-protocol/components/project-runtime/list/list.go
> +	"github.com/erda-project/erda/modules/apps/personal-workbench/component-protocol/types"
It's not good to use `personal-workbench`'s common types in dop side.

2022-04-30 14:15 UTC, sfwn commented on modules/dop/component-protocol/components/project-runtime/list/list.go
> +	"github.com/erda-project/erda/modules/apps/personal-workbench/component-protocol/types"
There are many other places with the same problem.

2022-05-06 03:17 UTC, sfwn requested changes
dingtalktest should not be an app. It's a functional provider.
What do you think @luobily @Effet

2022-05-06 03:18 UTC, sixther-dc commented
> 
these code will be deleted, next pr.

2022-05-07 02:25 UTC, luobily commented
/approve

2022-05-07 02:31 UTC, sfwn approved these changes

2022-05-07 02:31 UTC, sfwn commented
/approve

2022-05-07 02:31 UTC, merged