fix(pipeline): pipeline status is always running when all tasks are disabled
erda-project/erda pull request #4816
Opened 2022-05-09 07:13 UTC by chengjoey

#### What this PR does / why we need it:
pipeline status is always running when all tasks are disabled

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=311116&iterationID=1190&pId=0&type=BUG)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |    Fix the bug that pipeline status is always running when all tasks are disabled          |
| 🇨🇳 中文    | 修复了流水线的状态一直running中当所有任务都被禁用             |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-05-09 09:53 UTC, sfwn requested changes

2022-05-09 09:53 UTC, sfwn commented on modules/pipeline/providers/reconciler/pipeline_reconciler_impl.go
> +			pr.log.Panicf("invalid type of value in processedTasks")
type ? pid?

2022-05-09 09:53 UTC, sfwn commented on modules/pipeline/providers/reconciler/pipeline_reconciler_impl_test.go
> +	//dbClient := &dbclient.Client{}
delete this line

2022-05-09 09:58 UTC, chengjoey commented on modules/pipeline/providers/reconciler/pipeline_reconciler_impl_test.go
> +	//dbClient := &dbclient.Client{}
deleted

2022-05-09 09:59 UTC, sfwn submitted a review, later dismissed

2022-05-09 09:59 UTC, sfwn commented
/approve

2022-05-09 11:19 UTC, sfwn approved these changes

2022-05-09 11:24 UTC, merged

2022-05-09 11:34 UTC, chengjoey commented
/cherry-pick release/2.2-beta.1

2022-05-23 03:58 UTC, chengjoey commented
/cherry-pick release/2.1