feat(pipeline): edge-side pipeline support register webhook and dispatch events
erda-project/erda pull request #4961
Opened 2022-05-26 14:39 UTC by chengjoey

#### What this PR does / why we need it:
edge-side pipeline support register webhook client and dispatch events

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=313658&iterationID=1218&pId=0&type=TASK)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  edge-side pipeline support register webhook client and dispatch events             |
| 🇨🇳 中文    |   边缘pipeline支持注册webhook并发送事件           |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-06-09 06:11 UTC, sfwn requested changes

2022-06-09 06:11 UTC, sfwn commented on internal/tools/pipeline/events/event_pipeline.go
> +	if !e.edgeRegister.IsEdge() {
wrap it

2022-06-09 09:51 UTC, chengjoey commented on internal/tools/pipeline/events/event_pipeline.go
> +	if !e.edgeRegister.IsEdge() {
adjusted

2022-06-10 11:46 UTC, sfwn commented on internal/tools/pipeline/providers/edgepipeline_register/webhook.go
> +	p.Register.Add(http.MethodGet, "/api/dice/eventbox/webhooks", p.listWebHook)
separate webhook to a distinct provider, and share to eventbox.

2022-06-10 11:46 UTC, sfwn approved these changes

2022-06-10 11:46 UTC, sfwn commented on internal/tools/pipeline/providers/edgepipeline_register/webhook.go
> +	p.Register.Add(http.MethodGet, "/api/dice/eventbox/webhooks", p.listWebHook)
do it in another pr.

2022-06-10 11:48 UTC, sfwn commented
/approve

2022-06-10 11:48 UTC, merged