fix(pipeline): Solve the problem of automatically opening the timing when on push
erda-project/erda pull request #5090
Opened 2022-06-21 04:01 UTC by littlejiancc

#### What this PR does / why we need it:
Solve the problem of automatically opening the timing when on push

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjgwLDEyOTddLCJhc3NpZ25lZSI6WyIxMDAxMjYxIl19&id=319317&iterationID=1280&pId=0&type=BUG)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      Solve the problem of automatically opening the timing when on push        |
| 🇨🇳 中文    |       解决on push的时候自动开启定时问题       |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-06-21 08:01 UTC, sfwn commented
rebase master please

2022-06-21 08:56 UTC, sfwn requested changes

2022-06-21 08:56 UTC, sfwn commented on internal/tools/pipeline/providers/cron/cron.service.go
> +		return s.addIntoPipelineCrond(createCron)
why move to the function end

2022-06-21 08:56 UTC, sfwn commented on internal/tools/pipeline/providers/cron/cron.service_test.go
> +				t.Errorf("addIntoPipelineCrond() error = %v, wantErr %v", err, tt.wantErr)
assert error is meaningless

2022-06-21 09:17 UTC, littlejiancc commented on internal/tools/pipeline/providers/cron/cron.service_test.go
> +				t.Errorf("addIntoPipelineCrond() error = %v, wantErr %v", err, tt.wantErr)
done

2022-06-22 01:56 UTC, sfwn approved these changes

2022-06-22 01:56 UTC, merged

2022-06-22 06:59 UTC, littlejiancc commented
/cherry-pick release/2.2