refactor: make resource pkg calculate pipeline task
erda-project/erda pull request #5111
Opened 2022-06-23 07:32 UTC by chengjoey

#### What this PR does / why we need it:
make resource pkg calculate pipeline task

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |   make resource pkg calculate pipeline task           |
| 🇨🇳 中文    |     抽出pipeline资源计算到pkg包         |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-06-23 09:23 UTC, sfwn requested changes
maybe no need resource pkg.
just change `func (s *PipelineSvc) calculatePipelineResources` into provider.

2022-06-24 01:59 UTC, sfwn requested changes
merge pkg/resource into provider.

2022-06-24 02:38 UTC, chengjoey commented
> merge pkg/resource into provider.

done

2022-06-24 05:48 UTC, sfwn requested changes

2022-06-24 05:48 UTC, sfwn commented on internal/tools/pipeline/providers/resource/provider.go
> +	s.bdl = bundle.New()
this is a bundle without any clients

2022-06-24 06:20 UTC, chengjoey commented on internal/tools/pipeline/providers/resource/provider.go
> +	s.bdl = bundle.New()
no usage bundle, deleted

2022-06-24 06:25 UTC, sfwn approved these changes

2022-06-24 06:25 UTC, sfwn commented
/approve

2022-06-24 06:25 UTC, merged