fix(dop,pipeline): Deleting pipeline definitions and sources when deleting project and application
erda-project/erda pull request #5148
Opened 2022-06-29 09:16 UTC by littlejiancc

#### What this PR does / why we need it:
Deleting pipeline definitions and sources when deleting project and application

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjk3XSwiYXNzaWduZWUiOlsiMTAwMTI2MSJdfQ%3D%3D&id=315826&iterationID=1297&pId=0&type=BUG)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |     Deleting pipeline definitions and sources when deleting project and application         |
| 🇨🇳 中文    |      删除项目和应用时删除流水线定义        |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-07-01 06:17 UTC, sfwn requested changes
stop cron when pipeline definition deleted

2022-07-01 06:17 UTC, sfwn commented on internal/tools/pipeline/providers/definition/db/define.go
> +		Update(map[string]interface{}{"soft_deleted_at": time.Now().UnixNano() / 1e6})
use `time.Now().UnixMilli())`

2022-07-01 06:17 UTC, sfwn commented on .erda/migrations/pipeline/20220629-pipeline-definition-add-remote.sql
> +ALTER TABLE `pipeline_definition` ADD COLUMN  `remote` varchar(100) NOT NULL DEFAULT '' COMMENT 'remote';
use `pipeline_source_id` is enough.

2022-07-01 06:17 UTC, sfwn commented on .erda/migrations/pipeline/20220629-pipeline-definition-add-remote.sql
> +ALTER TABLE `pipeline_definition_extra` ADD COLUMN  `remote` varchar(100) NOT NULL DEFAULT '' COMMENT 'remote';
`pipeline_definition_extra` link `pipeline_source_id`.

2022-07-13 03:15 UTC, sfwn requested changes

2022-07-13 03:15 UTC, sfwn commented on api/proto/core/pipeline/definition/definition.proto
> +    int64 ExecutedActionNum = 23;
why this field start with uppercase?

2022-07-13 03:15 UTC, sfwn commented on api/proto/core/pipeline/definition/definition.proto
> +    int64 ExecutedActionNum = 18;
and this

2022-07-13 03:15 UTC, sfwn commented on internal/apps/dop/endpoints/application.go
> +		logrus.Errorf("failed to delete projectPipeline by app, err: %v", err)
abort app deletion, or project pipeline leaked.

2022-07-13 03:15 UTC, sfwn commented on internal/tools/pipeline/providers/definition/db/define.go
> +	_, err := session.Table("pipeline_definition").
use model.TableName function

2022-07-13 03:15 UTC, sfwn commented on internal/tools/pipeline/providers/definition/db/define.go
> +	err := session.Table("pipeline_definition").Alias("d").
same here

2022-07-13 03:15 UTC, sfwn commented on internal/tools/pipeline/providers/definition/db/define_extra.go
> +	_, err := session.Table("pipeline_definition_extra").
same

2022-07-13 03:15 UTC, sfwn commented on internal/tools/pipeline/providers/definition/pipeline_definition.go
> +	session.Begin()
handle error

2022-07-13 03:15 UTC, sfwn commented on internal/tools/pipeline/providers/definition/pipeline_definition.go
> +		session.Rollback()
rollback in defer

2022-07-13 03:15 UTC, sfwn commented on internal/tools/pipeline/providers/source/db/source.go
> +	if err := session.Where("remote LIKE ?", remote+"%").
let variable name clearer.
you'd better use `remotePrefix`.

2022-07-13 03:15 UTC, sfwn commented on internal/tools/pipeline/providers/source/pipeline_source.go
> +	session.Begin()
same

2022-07-13 07:05 UTC, littlejiancc commented on api/proto/core/pipeline/definition/definition.proto
> +    int64 ExecutedActionNum = 23;
done

2022-07-13 07:08 UTC, littlejiancc commented on internal/tools/pipeline/providers/definition/db/define.go
> +	_, err := session.Table("pipeline_definition").
done

2022-07-13 07:08 UTC, littlejiancc commented on internal/tools/pipeline/providers/definition/db/define.go
> +	err := session.Table("pipeline_definition").Alias("d").
done

2022-07-13 07:09 UTC, littlejiancc commented on internal/tools/pipeline/providers/definition/pipeline_definition.go
> +	session.Begin()
done

2022-07-13 07:09 UTC, littlejiancc commented on internal/tools/pipeline/providers/definition/db/define_extra.go
> +	_, err := session.Table("pipeline_definition_extra").
done

2022-07-13 07:35 UTC, littlejiancc commented on internal/tools/pipeline/providers/definition/pipeline_definition.go
> +		session.Rollback()
done

2022-07-13 07:38 UTC, littlejiancc commented on internal/tools/pipeline/providers/source/pipeline_source.go
> +	session.Begin()
done

2022-07-13 08:22 UTC, sfwn approved these changes

2022-07-13 08:58 UTC, merged