refactor(pipeline): refactor queue management to pb provider
erda-project/erda pull request #5199
Opened 2022-07-07 11:22 UTC by chengjoey

#### What this PR does / why we need it:
refactor queue management to pb provider

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |   refactor queue management to pb provider           |
| 🇨🇳 中文    |     pipeline队列的pb provider迁移         |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-07-07 11:24 UTC, chengjoey commented
![image](https://user-images.githubusercontent.com/30427474/177762256-2c786feb-0e2d-4e4a-9d88-4a9ed6e50f1f.png)
![image](https://user-images.githubusercontent.com/30427474/177762320-dbcd9169-3d34-437f-a760-5a28c1e4a5f2.png)
![image](https://user-images.githubusercontent.com/30427474/177762402-c49a700e-7291-4fb2-9bba-8c4ffc62bd72.png)

2022-07-08 03:30 UTC, sfwn requested changes

2022-07-08 03:30 UTC, sfwn commented on internal/tools/pipeline/dbclient/op_pipeline_queue.go
> +	q.TimeUpdated = timestamppb.New(timeUpdated)
use `pbutil.gettimestamp`

2022-07-08 03:40 UTC, sfwn approved these changes

2022-07-08 05:32 UTC, sfwn commented
/approve

2022-07-08 05:32 UTC, merged