fix: aop `autotest_cookie_keep_before` plugin merge all cookies from report
erda-project/erda pull request #5223
Opened 2022-07-12 07:39 UTC by chengjoey

#### What this PR does / why we need it:
aop `autotest_cookie_keep_before` plugin merge all cookies from report

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=325656&iterationID=1321&pId=0&type=BUG)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |   aop `autotest_cookie_keep_before` plugin merge all cookies from report           |
| 🇨🇳 中文    |     修复了自动化测试缺失cookie的问题         |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-07-13 02:09 UTC, sfwn requested changes

2022-07-13 02:09 UTC, sfwn commented on internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie.go
> +				return cookies, nil
how about `continue` if there are multiple headerSetCookie?

2022-07-13 02:09 UTC, sfwn commented on internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/plugin.go
> +			rlog.TErrorf(ctx.SDK.Pipeline.ID, ctx.SDK.Task.ID, "failed to get cookies from meta(continue next report), err: %, meta: %v", err, v.Meta)
return error here

2022-07-13 02:37 UTC, chengjoey commented on internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/cookie.go
> +				return cookies, nil
adjusted, break if field == apitestsv2.HeaderSetCookie

2022-07-13 02:37 UTC, chengjoey commented on internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/plugin.go
> +			rlog.TErrorf(ctx.SDK.Pipeline.ID, ctx.SDK.Task.ID, "failed to get cookies from meta(continue next report), err: %, meta: %v", err, v.Meta)
adjusted

2022-07-13 02:54 UTC, sfwn requested changes

2022-07-13 02:54 UTC, sfwn commented on internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/plugin.go
> +			rlog.TErrorf(ctx.SDK.Pipeline.ID, ctx.SDK.Task.ID, "failed to get cookies from meta(continue next report), err: %, meta: %v", err, v.Meta)
what is `continue next report`?

2022-07-13 03:03 UTC, chengjoey commented on internal/tools/pipeline/aop/plugins/task/autotest_cookie_keep_before/plugin.go
> +			rlog.TErrorf(ctx.SDK.Pipeline.ID, ctx.SDK.Task.ID, "failed to get cookies from meta(continue next report), err: %, meta: %v", err, v.Meta)
deleted `continue next report`

2022-07-13 03:24 UTC, sfwn approved these changes

2022-07-13 03:24 UTC, sfwn commented
/approve

2022-07-13 03:24 UTC, merged

2022-07-14 01:20 UTC, chengjoey commented
/cherry-pick release/2.2

2022-07-14 11:09 UTC, chengjoey commented
/cherry-pick release/2.3-beta.2