fix(dop): Solve the problem that the encrypted value is empty when batch update
erda-project/erda pull request #5291
Opened 2022-07-27 03:55 UTC by littlejiancc

#### What this PR does / why we need it:
Solve the problem that the encrypted value is empty when batch update

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=329181&iterationID=1337&pId=0&type=BUG)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |     Solve the problem that the encrypted value is empty when batch update         |
| 🇨🇳 中文    |      解决批量修改的时候加密value为空问题        |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-07-27 05:46 UTC, sfwn requested changes

2022-07-27 05:46 UTC, sfwn commented on internal/apps/dop/providers/cms/cicdcmsservice.go
> +func GetKeysAndValueMap(req *CICDCmsCreateOrUpdateRequest) (keys []string, valueMap map[string]*cmspb.PipelineCmsConfigValue) {
no need export this method.

2022-07-27 05:48 UTC, littlejiancc commented on internal/apps/dop/providers/cms/cicdcmsservice.go
> +func GetKeysAndValueMap(req *CICDCmsCreateOrUpdateRequest) (keys []string, valueMap map[string]*cmspb.PipelineCmsConfigValue) {
done

2022-07-27 07:35 UTC, sfwn approved these changes

2022-07-27 07:35 UTC, sfwn commented
/approve

2022-07-27 07:35 UTC, merged

2022-08-01 04:02 UTC, littlejiancc commented
/cherry-pick release/2.3-beta.3