refactor: manual trigger mode pipeline use run-user permission
erda-project/erda pull request #5359
Opened 2022-08-08 06:08 UTC by chengjoey

#### What this PR does / why we need it:
manual trigger mode pipeline use run-user permission

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=331588&iterationID=1354&pId=0&type=REQUIREMENT)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |   manual trigger mode pipeline use run-user permission           |
| 🇨🇳 中文    |      手动触发的流水线所有节点按执行者权限决定        |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-08-08 08:03 UTC, sfwn requested changes
Please add a doc for these roles.
Refer to a doc repo pr.

2022-08-10 03:16 UTC, chengjoey commented
> Please add a doc for these roles. Refer to a doc repo pr.

#https://github.com/erda-project/docs/pull/244

2022-08-10 03:49 UTC, sfwn approved these changes

2022-08-10 03:49 UTC, sfwn commented
/approve

2022-08-10 03:50 UTC, merged