refactor(pipeline): pipeline label service to provider
erda-project/erda pull request #5474
Opened 2022-09-02 02:31 UTC by chengjoey

#### What this PR does / why we need it:
refactor pipeline label service to pb provider

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |    refactor pipeline label service to pb provider           |
| 🇨🇳 中文    |       把流水线的label重构为provider       |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-09-13 02:24 UTC, sfwn requested changes

2022-09-13 02:24 UTC, sfwn commented on api/proto/core/pipeline/label/label.proto
> +  repeated uint64 targetIds = 3;
use json_name tag

2022-09-13 02:24 UTC, sfwn commented on internal/tools/pipeline/providers/label/label.service.impl.go
> +	// if UnMatchKeys and TargetIds not empty, find targetID by MatchKeys from db then filter targetID not in TargetIds
same

2022-09-13 12:14 UTC, chengjoey commented on internal/tools/pipeline/providers/label/label.service.impl.go
> +	// if UnMatchKeys and TargetIds not empty, find targetID by MatchKeys from db then filter targetID not in TargetIds
adjusted

2022-09-13 12:14 UTC, chengjoey commented on api/proto/core/pipeline/label/label.proto
> +  repeated uint64 targetIds = 3;
adjusted

2022-09-14 01:42 UTC, sfwn approved these changes

2022-09-14 01:42 UTC, sfwn commented
/approve

2022-09-14 01:43 UTC, merged