fix: optimize k8s resource gc logic
erda-project/erda pull request #5531
Opened 2022-09-23 07:08 UTC by chengjoey

#### What this PR does / why we need it:
optimize k8s resource gc logic

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?id=340074&iterationID=1403&pId=0&type=TASK)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |     optimize k8s resource gc logic           |
| 🇨🇳 中文    |      优化k8s资源gc的逻辑        |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-09-26 09:05 UTC, sfwn requested changes

2022-09-27 01:29 UTC, chengjoey commented on internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
> +func (k *K8sFlink) CleanUP(ctx context.Context, namespace string) error {
adjusted

2022-09-27 01:29 UTC, chengjoey commented on internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sjob/k8sjob.go
> +func (k *K8sJob) CleanUP(ctx context.Context, namespace string) error {
adjusted

2022-09-27 02:05 UTC, sfwn approved these changes

2022-09-27 02:05 UTC, sfwn commented
/approve

2022-09-27 02:30 UTC, merged