feat(dop): exported test case excel file add updatedAt filed
erda-project/erda pull request #5583
Opened 2022-10-26 06:28 UTC by chengjoey

#### What this PR does / why we need it:
exported test case excel file add updatedAt filed

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=345326&iterationID=1440&pId=0&type=REQUIREMENT)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  exported test case excel file add updatedAt filed            |
| 🇨🇳 中文    |     手动测试导出excel文件增加更新时间字段         |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2022-10-26 07:51 UTC, sfwn requested changes

2022-10-26 07:51 UTC, sfwn commented on internal/apps/dop/services/testcase/export_excel.go
>  			// 只合并前5列基础信息
maybe this comment should be updated?

2022-10-26 08:06 UTC, chengjoey commented on internal/apps/dop/services/testcase/export_excel.go
>  			// 只合并前5列基础信息
updated

2022-11-01 03:27 UTC, sfwn approved these changes

2022-11-01 03:28 UTC, sfwn commented
/approve

2022-11-01 03:28 UTC, merged