base image support
erda-project/erda pull request #56
Opened 2021-03-25 09:45 UTC by recallsong

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
base image support.
remove duplicated .gitignore content.
update go.mod.

#### Special notes for your reviewer:
```
```

#### Specified Reivewers:
/assgin @liuhaoyang 

#### Does this PR introduce a user-facing change?
```release-note
```

#### Additional documentation usage docs, etc.:
```docs

```

2021-03-25 09:58 UTC, sfwn requested changes

2021-03-25 09:58 UTC, sfwn commented on .gitignore
> -# Dependency directories (remove the comment below to include it)
why delete these lines?

these files should be gitignore.

2021-03-25 09:59 UTC, sfwn commented on .gitignore
> -# Dependency directories (remove the comment below to include it)
ok i see it's duplicated

2021-03-25 15:14 UTC, liuhaoyang approved these changes
/lgtm

2021-03-26 02:42 UTC, liuhaoyang approved these changes
/lgtm

2021-03-26 14:58 UTC, merged