subscribe issue
erda-project/erda pull request #562
Opened 2021-06-04 09:23 UTC by QvodSoldier

#### What type of this PR
/kind feature

#### What this PR does / why we need it:
Added subscription function, But it does not include sending messages to subscribers

#### Specified Reviewers:
/assign @Effet

2021-06-10 02:12 UTC, Effet requested changes

2021-06-10 02:12 UTC, Effet commented on modules/openapi/api/apis/cmdb/cmdb_issue_unsubscribe.go
> +	BackendPath: "/api/issues/<id>/unsubscribe",
/api/issues/<id>/actions/unsubscribe

2021-06-10 02:27 UTC, QvodSoldier commented on modules/openapi/api/apis/cmdb/cmdb_issue_unsubscribe.go
> +	BackendPath: "/api/issues/<id>/unsubscribe",
done

2021-06-10 07:19 UTC, Effet requested changes

2021-06-10 07:19 UTC, Effet commented on modules/cmdb/dao/issue_subscriber.go
> +// TableName 表名
english required

2021-06-10 07:19 UTC, Effet commented on .erda/migrations/cmdb/20210610-addIssueSubscriber.sql
> +  `created_at` datetime DEFAULT NULL COMMENT '表记录创建时间',
english required

2021-06-10 07:19 UTC, Effet commented on modules/cmdb/endpoints/issue.go
> +	// data 返回 ID
english required

2021-06-10 07:19 UTC, Effet commented on modules/cmdb/endpoints/issue.go
> +	// data 返回 ID
english required

2021-06-10 09:13 UTC, QvodSoldier commented on modules/cmdb/endpoints/issue.go
> +	// data 返回 ID
done

2021-06-10 09:14 UTC, QvodSoldier commented on modules/cmdb/endpoints/issue.go
> +	// data 返回 ID
done

2021-06-10 09:14 UTC, QvodSoldier commented on .erda/migrations/cmdb/20210610-addIssueSubscriber.sql
> +  `created_at` datetime DEFAULT NULL COMMENT '表记录创建时间',
done

2021-06-11 02:32 UTC, QvodSoldier commented on modules/cmdb/dao/issue_subscriber.go
> +// TableName 表名
done

2021-06-15 01:51 UTC, Effet approved these changes

2021-06-15 01:52 UTC, Effet commented
/approve

2021-06-15 02:07 UTC, merged