feat: add postgres-exporter
erda-project/erda pull request #5730
Opened 2023-03-02 10:10 UTC by dspo

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |              |
| 🇨🇳 中文    |              |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2023-03-02 11:44 UTC, dspo commented
@iutx @sfwn

2023-03-03 02:14 UTC, dspo commented on internal/apps/msp/resource/deploy/handlers/postgresql/postgresql.go
>  		// envs
postgre's dice.yaml
https://github.com/erda-project/erda-addons-enterprise/blob/master/addons/postgresql/1.0.0/dice.yml

2023-03-03 02:15 UTC, dspo commented on internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
> +			}, ","),
Kong 的默认插件写在环境变量中, 硬编码到代码里, 是否合适, 还是应该写到 kong addon 的  dice.yml 里?

2023-03-03 02:17 UTC, dspo commented on internal/apps/msp/resource/deploy/handlers/postgresql/postgresql.go
> +		}
postgre's dice.yaml
https://github.com/erda-project/erda-addons-enterprise/blob/master/addons/postgresql/1.0.0/dice.yml

2023-03-03 02:23 UTC, iutx commented on internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
> +			}, ","),
可以看看后续是否变动频繁，当然可以写到 kong 的 dice.yml 中更合适

2023-03-03 02:27 UTC, dspo commented on internal/apps/msp/resource/deploy/handlers/apigateway/apigateway.go
> +			}, ","),
已提交到 kong 的 dice.yaml

https://github.com/erda-project/erda-addons-enterprise/pull/56/files#diff-99a93e5bf2ff0e98c21183c208f21f2f443a8aae81b228654301bfeef7f094a2

2023-03-03 02:57 UTC, sfwn requested changes

2023-03-03 02:57 UTC, sfwn commented on build/dockerfiles/Dockerfile
> +RUN arch="$(dpkg --print-architecture)"; arch="${arch##*-}"; \
You just made some changes here, so let's make a judgment: only install niginx for hepa or all-in-one.

2023-03-03 02:57 UTC, sfwn commented on internal/apps/msp/resource/deploy/handlers/postgresql/postgresql.go
> +		}
why ignored

2023-03-04 09:05 UTC, dspo commented on internal/apps/msp/resource/deploy/handlers/postgresql/postgresql.go
> +		}
这个 for 循环后面的逻辑是对每一个 service 加环境变量、健康检查等，而这些已经在 addon 的 dice.yml 配置好了，无须在代码中再为其配置。

2023-03-13 10:10 UTC, closed without merging