fix: kong sbac and csrf plugin parse for specified routeId
erda-project/erda pull request #5745
Opened 2023-03-17 07:14 UTC by wangzhuzhen

#### What this PR does / why we need it:
Fix the bug that:  when set kong sbac and csrf policy for specified API without routeId result global kong policy., so all existed APIs can not accessed。

#### Specified Reviewers:

/assign @luobily @iutx @dspo @sixther-dc 

#### ChangeLog
Bugfix： Fix the bug that when set kong sbac and csrf policy for specified API without routeId result global kong policy., so all existed APIs can not accessed（修复了 kong 设置 sbac和 csrf 策略不带 roueId 导致设置成全局变量.）

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      Fix the bug that when set kong sbac and csrf policy for specified API without routeId result global kong policy., so all existed APIs can not accessed         |
| 🇨🇳 中文    |     修复了 kong 设置 sbac和 csrf 策略不带 roueId 导致设置成全局变量         |

2023-03-24 08:20 UTC, sfwn requested changes

2023-03-24 08:20 UTC, sfwn commented on internal/tools/orchestrator/hepa/apipolicy/policies/built-in/policy.go
> +// forValidate 用于识别解析的目的，如果解析是用来做鱼 nginx 配置冲突相关的校验，则关于数据表、调用 kong 接口的操作都不会执行
what is '做鱼 nginx'

2023-03-24 08:21 UTC, wangzhuzhen commented on internal/tools/orchestrator/hepa/apipolicy/policies/built-in/policy.go
> +// forValidate 用于识别解析的目的，如果解析是用来做鱼 nginx 配置冲突相关的校验，则关于数据表、调用 kong 接口的操作都不会执行
多了个字

2023-03-24 08:22 UTC, merged

2023-04-04 06:03 UTC, sixther-dc commented
/cherry-pick  release/2.3