fix(pipeline): flinkcluster executor idempotent deletion task failure due to the returned type error
erda-project/erda pull request #5767
Opened 2023-03-30 02:38 UTC by chengjoey

#### What this PR does / why we need it:
fix flinkcluster idempotent deletion task failure due to the returned type error

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=371332&iterationID=1580&tab=BUG&type=BUG)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | Fix the bug that flinkcluster executor idempotent deletion task failure due to the returned type error             |
| 🇨🇳 中文    |   修复了flinkcluster由于返回类型错误导致的幂等删除任务失败的问题           |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2023-03-30 03:07 UTC, sfwn requested changes

2023-03-30 03:07 UTC, sfwn commented on internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
> -		return nil, fmt.Errorf("get flinkcluster %s in ns %s is err: %s", data.Name, data.Namespace, err.Error())
print err log here

2023-03-30 03:24 UTC, chengjoey commented on internal/tools/pipeline/pipengine/actionexecutor/plugins/k8sflink/flink.go
> -		return nil, fmt.Errorf("get flinkcluster %s in ns %s is err: %s", data.Name, data.Namespace, err.Error())
done~

2023-03-30 03:27 UTC, sfwn approved these changes

2023-03-30 03:27 UTC, sfwn commented
/approve

2023-03-30 04:02 UTC, merged

2023-03-31 09:12 UTC, chengjoey commented
/cherry-pick release/2.3