fix(dop): issues states always be default after refresh
erda-project/erda pull request #5802
Opened 2023-04-10 08:10 UTC by chengjoey

#### What this PR does / why we need it:
fix: issues states always be default after refresh

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |   Fix the bug that issues states always be default after refresh           |
| 🇨🇳 中文    |   修复了事项协同状态筛选总是在刷新后变成默认值的问题           |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2023-04-10 08:38 UTC, sfwn requested changes

2023-04-10 08:38 UTC, sfwn commented on internal/apps/dop/component-protocol/standard-components/issueFilter/conditions.go
> +func (f *FrontendConditions) IsEmpty() bool {
use reflect

2023-04-10 08:43 UTC, chengjoey commented on internal/apps/dop/component-protocol/standard-components/issueFilter/conditions.go
> +func (f *FrontendConditions) IsEmpty() bool {
done!

2023-04-11 02:30 UTC, sfwn approved these changes

2023-04-11 02:30 UTC, merged

2023-04-11 02:30 UTC, sfwn commented
/cherry-pick release/2.3