feat: reverse proxy for text/event-stream
erda-project/erda pull request #5842
Opened 2023-05-08 09:43 UTC by dspo

#### What this PR does / why we need it:
feat: reverse proxy for text/event-stream

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English  feat: reverse proxy for text/event-stream |
| 🇨🇳 中文    | 反向代理框架支持 text/event-stream 流式返回 |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2023-05-10 02:10 UTC, sfwn requested changes

2023-05-10 02:10 UTC, sfwn commented on cmd/ai-proxy/conf/routes.yml
> +    router:
why not use `/v1/embeddings`

2023-05-10 02:10 UTC, sfwn commented on internal/apps/ai-proxy/filters/audit/filter.go
> +	var l = ctx.Value(reverseproxy.LoggerCtxKey{}).(logs.Logger).Sub("Audit").Sub("OnHttpRequestInfor")
mismatched log sub.
you should provider a method to get logger and inject subs using reflect.

2023-05-10 02:10 UTC, sfwn commented on pkg/reverseproxy/reverseproxy.go
> +	// Issue 21096: tell backend applications that care about trailer support
whose issue?

2023-05-10 02:10 UTC, sfwn commented on pkg/reverseproxy/reverseproxy.go
> +type ReverseProxy struct {
Why not just embed the official reverse proxy?

2023-05-10 02:35 UTC, dspo commented on cmd/ai-proxy/conf/routes.yml
> +    pathMatcher: ""   # 不填写时, 默认为 `^/v1/models/([^/.]+)$`
因为 path 里有占位符 `{model}` 所以会转换成正则表达式 `^/v1/models/(?P<model>[^/.]+)$` 这样去匹配

2023-05-10 02:36 UTC, dspo commented on cmd/ai-proxy/conf/routes.yml
> +    router:
openai 没有 `/v1/embeddings` 这样的接口, `/openai/deployments/{deploymentId}/embeddings` 接口是 azure 特有的

2023-05-11 03:16 UTC, dspo commented on cmd/ai-proxy/conf/routes.yml
> +    router:
用到 `/v1/embeddings` 这个接口的时候再加

2023-05-11 03:16 UTC, dspo commented on internal/apps/ai-proxy/filters/audit/filter.go
> +	var l = ctx.Value(reverseproxy.LoggerCtxKey{}).(logs.Logger).Sub("Audit").Sub("OnHttpRequestInfor")
记个任务, 优化一下

2023-05-11 03:21 UTC, sfwn approved these changes

2023-05-11 03:21 UTC, sfwn commented
/approve

2023-05-11 03:21 UTC, merged

2023-05-11 03:31 UTC, dspo commented on internal/apps/ai-proxy/metrics/collector.go
> +
@sfwn 这会导致指标变成两倍吗 ?