feat: add manHour to iteration API
erda-project/erda pull request #5871
Opened 2023-05-22 08:20 UTC by dspo

#### What this PR does / why we need it:

feat: add manHour to iteration API

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | feat: add manHour to iteration API |
| 🇨🇳 中文    | 为迭代接口增加 manHour 信息 |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2023-05-23 02:04 UTC, sfwn requested changes

2023-05-23 02:04 UTC, sfwn commented on .erda/migrations/cmdb/20230522-interation-man-hour.sql
> +    ADD `man_hour` text COMMENT '迭代工时信息';
after `xxx` field.

2023-05-23 02:04 UTC, sfwn commented on apistructs/issue.go
> +	_ = json.Unmarshal([]byte(s), imh)
log for error

2023-05-24 08:01 UTC, dspo commented on .erda/migrations/cmdb/20230522-interation-man-hour.sql
> +    ADD `man_hour` text COMMENT '迭代工时信息';
need not to resolve

2023-05-25 02:11 UTC, sfwn approved these changes

2023-05-25 02:11 UTC, sfwn commented
/approve

2023-05-25 02:12 UTC, merged