feat: add key-auth
erda-project/erda pull request #5974
Opened 2023-07-06 07:38 UTC by dspo

#### What this PR does / why we need it:
feat: add key-auth

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | feat: add key-auth             |
| 🇨🇳 中文    | 增加 key-auth 插件             |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2023-07-06 08:03 UTC, dspo commented on api/proto/proto_fetcher.sh
> +OTEL_PROTO_REPO="https://ghproxy.com/https://github.com/open-telemetry/opentelemetry-proto.git"
@sfwn 是否可以修改 ?

2023-07-13 08:55 UTC, sfwn requested changes

2023-07-13 08:55 UTC, sfwn commented on .erda/ai-proxy/migrations/ai-proxy/20230425-filter-audit.sql
> +    `app_key_sha256`        CHAR(64)     NOT NULL DEFAULT '' COMMENT '请求使用的 app_key sha256 哈希值',
what is app_key?

2023-07-13 08:55 UTC, sfwn commented on .erda/ai-proxy/migrations/ai-proxy/20230706-credentials.sql
> +    `provider_name`     VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'AI 服务 Provider 名称',
enlarge field size

2023-07-13 08:55 UTC, sfwn commented on .erda/ai-proxy/migrations/ai-proxy/20230706-credentials.sql
> +    `provider_name`     VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'AI 服务 Provider 名称',
add examples in comment

2023-07-13 08:55 UTC, sfwn commented on .erda/ai-proxy/migrations/ai-proxy/20230706-credentials.sql
> +    `provider_instance` VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'AI 服务 Provider 实例 id',
`provider_instance_id`

2023-07-13 08:55 UTC, sfwn commented on api/proto/apps/aiproxy/provider.proto
> +      delete: "/api/ai-proxy/providers/{name}/{instanceId}"
/api/ai-proxy/providers/{name}/instances/{instanceId}

2023-07-13 08:55 UTC, sfwn commented on api/proto/proto_fetcher.sh
> +OTEL_PROTO_REPO="https://ghproxy.com/https://github.com/open-telemetry/opentelemetry-proto.git"
you'd better not.

2023-07-13 08:55 UTC, sfwn commented on cmd/ai-proxy/conf/providers.yml
> +    appKey: ${ env.OPENAI_API_KEY }
bad env name

2023-07-13 08:55 UTC, sfwn commented on cmd/ai-proxy/conf/providers.yml
> +    instanceId: terminus2
instanceId should be composed with resource_name & deployment_name

2023-07-13 09:11 UTC, dspo commented on cmd/ai-proxy/conf/providers.yml
>      scheme: https
remove default

2023-07-17 01:55 UTC, sixther-dc approved these changes
/approve

2023-07-17 01:56 UTC, sixther-dc approved these changes
/approve

2023-07-18 02:18 UTC, sfwn approved these changes

2023-07-18 02:18 UTC, sfwn commented
/approve

2023-07-18 02:18 UTC, merged