Feature/ai schema framework
erda-project/erda pull request #6010
Opened 2023-08-03 06:25 UTC by dspo

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | add ai function framework             |
| 🇨🇳 中文    | 添加 ai function 框架 |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2023-08-17 05:40 UTC, sfwn requested changes
Remove bin file

2023-08-17 05:40 UTC, sfwn commented on internal/pkg/ai-functions/sdk/client.go
> +	request.Header.Set("Authorization", "Bearer "+"e78c1fe49d704fda978041cb21770282") // todo: ak
what's this

2023-08-17 06:24 UTC, dspo commented on .erda/ai-proxy/migrations/ai-proxy/20230425-filter-audit.sql
> +    `req_func_call_name`    VARCHAR(128) NOT NULL COMMENT 'function_call name in request message',
留给你啦

2023-08-17 06:33 UTC, dspo commented on bundle/testcase.go
> +	resp, err := b.hc.Post("localhost:9095").Path("/api/testcases").
请实现 gRPC 接口或本地调用

2023-08-17 06:34 UTC, dspo commented on cmd/erda-server/bootstrap.yaml
> +  openAIOpenapi: ${OPENAI_OPENAPI:http://ai-proxy:8081}
rename to `openaiAddr`

2023-08-17 06:58 UTC, dspo commented on internal/pkg/ai-functions/sdk/client.go
> +	request.Header.Set("Authorization", "Bearer "+"e78c1fe49d704fda978041cb21770282") // todo: ak
```go
	// 在 request option 中添加认证信息: 以某组织下某用户身份调用 ai-proxy,
	// ai-proxy 中的 filter erda-auth 会回调 erda.cloud 的 openai, 检查该企业和用户是否有权使用 AI 能力
	ros := append(f.RequestOptions(), func(r *http.Request) {
		r.Header.Set("X-Ai-Proxy-Source", "erda.cloud") // todo: hard code source
		r.Header.Set("X-Ai-Proxy-Org-Id", base64.StdEncoding.EncodeToString([]byte(apis.GetOrgID(ctx))))
		r.Header.Set("X-Ai-Proxy-User-Id", base64.StdEncoding.EncodeToString([]byte(apis.GetUserID(ctx))))
	})
```

2023-08-18 08:06 UTC, sfwn approved these changes

2023-08-18 08:06 UTC, sfwn commented
/approve

2023-08-18 08:07 UTC, merged