fix(orchestrator): only redis versions greater than 6.0 are deployed using the operator
erda-project/erda pull request #6110
Opened 2023-10-27 08:58 UTC by chengjoey

#### What this PR does / why we need it:
only redis versions greater than 6.0 are deployed using the operator

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |    Fix the bug that only redis versions greater than 6.0 are deployed using the operator          |
| 🇨🇳 中文    |    修复了redis低于6.0版本使用operator发布失败的问题          |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2023-10-27 08:59 UTC, sfwn requested changes

2023-10-27 08:59 UTC, sfwn commented on internal/tools/orchestrator/services/addon/addon_deploy.go
> +		if capacity.RedisOperator && params.Plan == apistructs.AddonProfessional && version.Compare(addonSpec.Version, "6.2.10", ">=") {
add unit-test for version.compare

2023-10-27 09:06 UTC, chengjoey commented on internal/tools/orchestrator/services/addon/addon_deploy.go
> +		if capacity.RedisOperator && params.Plan == apistructs.AddonProfessional && version.Compare(addonSpec.Version, "6.2.10", ">=") {
done

2023-11-01 02:14 UTC, sfwn approved these changes

2023-11-01 02:14 UTC, sfwn commented
/approve

2023-11-01 09:48 UTC, merged