feat: add performance measurement range value
erda-project/erda pull request #6111
Opened 2023-10-30 07:29 UTC by jing-zhi

#### What this PR does / why we need it:

feat: add performance measurement range value

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=516226&iterationID=12560&tab=TASK&type=TASK)

#### Specified Reviewers:

/assign @chengjoey @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      feat: add performance measurement range value        |
| 🇨🇳 中文    |       支持自然年，上下班年维度的效能度量查询       |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2023-10-30 08:20 UTC, chengjoey approved these changes

2023-10-30 09:02 UTC, sfwn requested changes

2023-10-30 09:02 UTC, sfwn commented on internal/apps/dop/providers/efficiency_measure/efficiency_query.go
> +	RangeWorkingRequirementTotal    float64 `json:"rangeWorkingRequirementTotal" ch:"rangeWorkingRequirementTotal"`
Too many changes, separate into groups.

2023-10-30 09:02 UTC, sfwn commented on internal/apps/dop/providers/efficiency_measure/efficiency_query.go
> +           first_value(number_field_values[indexOf(number_field_keys,'personal_owner_bug_total')]) as first_owner_bug_total,
format it please.

2023-10-31 01:17 UTC, jing-zhi commented on internal/apps/dop/providers/efficiency_measure/efficiency_query.go
> +           first_value(number_field_values[indexOf(number_field_keys,'personal_owner_bug_total')]) as first_owner_bug_total,
ok

2023-10-31 01:18 UTC, jing-zhi commented on internal/apps/dop/providers/efficiency_measure/efficiency_query.go
> +	RangeWorkingRequirementTotal    float64 `json:"rangeWorkingRequirementTotal" ch:"rangeWorkingRequirementTotal"`
ok

2023-11-01 02:13 UTC, sfwn approved these changes

2023-11-01 02:13 UTC, sfwn commented
/approve

2023-11-01 02:13 UTC, merged