feat: add license agent openapi proxy
erda-project/erda pull request #6147
Opened 2023-11-22 08:36 UTC by CeerDecy

#### What this PR does / why we need it:

add license-agent openapi proxy

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @iutx @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | add license agent openapi proxy |
| 🇨🇳 中文    | 添加了对license-agent的openapi转发 |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2023-11-23 07:40 UTC, iutx reviewed
@CeerDecy

2023-11-23 07:40 UTC, iutx commented on internal/core/openapi/legacy/api/apis/license_agent/agent_license_feature_get.go
> +	"github.com/erda-project/erda/internal/core/openapi/legacy/api/apis"
Please modify the Go import order for all Go files.

2023-11-23 07:40 UTC, iutx commented on internal/core/openapi/legacy/api/apis/license_agent/agent_license_feature_get.go
> +package license_agent
Please identify the license for the project.

2023-11-23 07:40 UTC, iutx commented on go.sum
>  cloud.google.com/go v0.102.0/go.mod h1:oWcCzKlqJ5zgHQt9YsaeTY9KzIvjyy0ArmiBUgpQ+nc=
If you did not change the go.mod file, please avoid committing the go.sum content.

2023-12-28 02:34 UTC, iutx approved these changes
LGTM @sfwn

2023-12-28 02:44 UTC, sfwn requested changes

2023-12-28 02:44 UTC, sfwn commented on .erda/migrations/license-agent/20230927-license-base.sql
> +CREATE TABLE erda_licenses
use singular format for table name: `erda_license`

2023-12-28 02:44 UTC, sfwn commented on internal/core/openapi/legacy/api/apis/license_agent/agent_license_feature_get.go
> +	Path:        "/api/licenses/features",
strange path

2023-12-28 03:15 UTC, CeerDecy commented on internal/core/openapi/legacy/api/apis/license_agent/agent_license_feature_get.go
> +	Path:        "/api/licenses/features",
how about `/api/licenses/obtain` ?

2023-12-28 03:47 UTC, CeerDecy commented on internal/core/openapi/legacy/api/apis/license_agent/agent_license_feature_get.go
> +	Path:        "/api/licenses/features",
![image](https://github.com/erda-project/erda/assets/79098669/680886ec-0c54-49ee-858a-ec0ff153fbd9)

2023-12-28 03:52 UTC, sfwn approved these changes

2023-12-28 03:52 UTC, sfwn commented
/approve

2023-12-28 04:14 UTC, merged