perf(monitor): optimize writing logic and accelerate query logic to optimize user experience
erda-project/erda pull request #6175
Opened 2023-12-12 06:01 UTC by chengjoey

#### What this PR does / why we need it:
optimize writing logic and accelerate query logic to optimize user experience

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=554629&iterationID=-1&tab=TASK&type=TASK)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |   optimize writing logic and accelerate query logic to optimize user experience           |
| 🇨🇳 中文    |    优化了可持续观测数据的写入查询逻辑          |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2023-12-13 09:38 UTC, sfwn requested changes

2023-12-13 09:38 UTC, sfwn commented on go.mod
> +	github.com/pyroscope-io/pyroscope => github.com/chengjoey/pyroscope v0.0.0-20231212053618-a7841ab08cea
pyroscope pr merged.

2023-12-14 02:20 UTC, chengjoey commented on go.mod
> +	github.com/pyroscope-io/pyroscope => github.com/chengjoey/pyroscope v0.0.0-20231212053618-a7841ab08cea
done

2023-12-15 05:24 UTC, sfwn approved these changes

2023-12-15 05:24 UTC, sfwn commented
/approve

2023-12-15 05:25 UTC, merged