feat: add permission checking logic to the notification group service
erda-project/erda pull request #6206
Opened 2023-12-29 03:49 UTC by CeerDecy

#### What this PR does / why we need it:

Add permission checking logic to the notification group service

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      Add permission checking logic to the notification group service        |
| 🇨🇳 中文    |       通知组服务添加权限校验逻辑       |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-01-12 06:21 UTC, iutx reviewed
@CeerDecy

2024-01-12 06:21 UTC, iutx commented on internal/core/messenger/notifygroup/group.service.go
> +func (n *notifyGroupService) getIdentityInfo(ctx context.Context) (apistructs.IdentityInfo, error) {
Please verify whether there are reusable elements in the project.

2024-01-12 06:21 UTC, iutx commented on internal/apps/msp/apm/notifygroup/provider.go
> +		type NotifyService = notifygroup.NotifyGroupServiceServer
Err protobuf source

2024-01-12 06:21 UTC, iutx commented on internal/core/messenger/notifygroup/group.service.go
> +	ctx = transport.WithHeader(ctx, metadata.New(map[string]string{httputil.InternalHeader: "true"}))
Incorrect internal-client injection

2024-01-12 07:02 UTC, CeerDecy commented on internal/core/messenger/notifygroup/group.service.go
> +	ctx = transport.WithHeader(ctx, metadata.New(map[string]string{httputil.InternalHeader: "true"}))
all done

2024-01-13 04:10 UTC, iutx approved these changes
LGTM @sfwn  
The code change depends on the frontend pull request.

2024-01-13 04:11 UTC, iutx commented
Please ensure that the CI checks pass. @CeerDecy

2024-01-15 09:49 UTC, iutx approved these changes
verified. @sfwn

2024-01-16 07:58 UTC, CeerDecy commented on internal/apps/msp/apm/notifygroup/notifygroup.service.go
> +	c = transport.WithHeader(c, metadata.New(map[string]string{httputil.InternalHeader: "true"}))
done

2024-01-17 03:04 UTC, sfwn requested changes

2024-01-17 03:04 UTC, sfwn commented on internal/apps/msp/apm/notifygroup/notifygroup.service.go
> +	c := apis.WithInternalClientContext(ctx, discover.MSP())
`discover.MSP()` will return the address of msp.
You should use `discover.SvcMSP` instead.

2024-01-17 05:54 UTC, sfwn approved these changes

2024-01-17 05:54 UTC, sfwn commented
/approve

2024-01-17 05:58 UTC, merged