feat: refactoring DaemonSet and supporting `k8s-snippet` in dice.yml
erda-project/erda pull request #6258
Opened 2024-01-26 08:34 UTC by CeerDecy

#### What this PR does / why we need it:

1. support k8s-snippet in daemonset
2. refactoring daemonset to interact with apiserver from http to client-go
3. default published application injection NODE_NAME, derived from spec.nodeName

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      refactoring DaemonSet and supporting `k8s-snippet` in dice.yml        |
| 🇨🇳 中文    |      重构 DaemonSet 并支持在 dice.yml 中的"k8s-snippet"        |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-01-26 08:46 UTC, iutx requested changes
@CeerDecy Please optimize the code.

2024-01-26 08:46 UTC, iutx commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/daemonset/daemonset.go
> +	addr string
Remove unused var.

2024-01-26 08:46 UTC, iutx commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/daemonset/daemonset.go
> +	PatchStruct struct {
Use common data structures that can be presented in deployment、daemonset.

2024-01-26 08:46 UTC, iutx commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
> +func getDeployName(service *apistructs.Service) string {
This portion is unrelated to `k8s.go` and should be moved to the utility class.

2024-01-29 03:00 UTC, iutx requested changes
@CeerDecy

2024-01-29 03:01 UTC, iutx commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment.go
> +	LabelKeyPrefix          = "Annotations/"
e.g.  Namespace、Envs、Annotations

2024-01-29 09:14 UTC, iutx commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/daemonset/daemonset.go
> +	types2 "github.com/erda-project/erda/internal/tools/orchestrator/scheduler/executor/plugins/k8s/types"
The issue is not resolved; please resubmit. @CeerDecy

2024-01-29 09:16 UTC, iutx requested changes

2024-01-29 09:16 UTC, iutx commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/daemonset/daemonset.go
> +	types2 "github.com/erda-project/erda/internal/tools/orchestrator/scheduler/executor/plugins/k8s/types"
Unresolved naming issues persist. @CeerDecy

2024-01-31 01:44 UTC, iutx requested changes
@CeerDecy 
Please review the code again and address the issues.

2024-01-31 01:44 UTC, iutx commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/daemonset/daemonset.go
> +	k8stypes "github.com/erda-project/erda/internal/tools/orchestrator/scheduler/executor/plugins/k8s/types"
Maintain the use of 'types' for references within the component; use 'k8stypes' to identify `k8s.io/apimachinery/pkg/types` similar to 'k8serrors.

2024-01-31 01:44 UTC, iutx commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/deployment/deployment.go
> +	k8stypes "github.com/erda-project/erda/internal/tools/orchestrator/scheduler/executor/plugins/k8s/types"
The same issue persists.

2024-02-19 02:52 UTC, iutx approved these changes
LGTM. @sfwn

2024-03-08 03:39 UTC, sfwn approved these changes

2024-03-08 03:39 UTC, sfwn commented
/approve

2024-03-08 03:39 UTC, merged