fix: OOM caused by the `steve` in the `cmp`
erda-project/erda pull request #6278
Opened 2024-02-20 09:21 UTC by CeerDecy

#### What this PR does / why we need it:

fix: OOM caused by the `steve` in the `cmp`

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       fix OOM caused by the `steve` in the `cmp`       |
| 🇨🇳 中文    |      修复cmp模块中steve导致的OOM        |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-03-19 06:54 UTC, iutx requested changes
@CeerDecy

2024-03-19 06:54 UTC, iutx commented on cmd/erda-server/bootstrap.yaml
> +  cache_size: 64
Add environment variable extensions.

2024-03-19 06:54 UTC, iutx commented on internal/apps/cmp/steve/aggregator.go
> +	ctx := transport.WithHeader(a.Ctx, metadata.New(map[string]string{httputil.InternalHeader: "true"}))
Use built-in method.

2024-03-19 06:54 UTC, iutx commented on internal/apps/cmp/steve/aggregator.go
> +	cluster, err := a.clusterSvc.GetCluster(ctx, &clusterpb.GetClusterRequest{IdOrName: key.(string)})
Assert and intercept at the function beginning.

2024-03-19 06:54 UTC, iutx commented on internal/apps/cmp/steve/aggregator.go
> +	//g, ok := a.servers.Load(clusterName)
Remove unuse code.

2024-03-19 06:54 UTC, iutx commented on internal/apps/cmp/steve/aggregator.go
> +func (a *Aggregator) prepareSteveServer(clusterInfo *clusterpb.ClusterInfo) {
clusterInfo != nil

2024-03-19 06:54 UTC, iutx commented on internal/apps/cmp/steve/aggregator.go
> +		//a.server.Remove(clusterInfo.Name)
Remove unuse code.

2024-03-19 06:54 UTC, iutx commented on internal/apps/cmp/steve/aggregator.go
> +	//a.servers.Delete(clusterName)
Remove unuse code.

2024-03-19 06:54 UTC, iutx commented on internal/apps/cmp/steve/aggregator.go
> +	//s, ok := a.servers.Load(clusterName)
Remove unuse code.

2024-03-19 06:54 UTC, iutx commented on internal/apps/cmp/steve/aggregator.go
> -	clusters, err := a.listClusterByType("k8s", "edas")
Please add this part of logic during load function.

2024-03-19 06:54 UTC, iutx commented on internal/apps/cmp/steve/aggregator.go
> +	servers := a.server.GetALL(false)
Is `GetALL` params still false?

2024-06-06 02:04 UTC, iutx submitted a review, later dismissed
/LGTM
PTAL :) @sfwn

2024-07-02 05:25 UTC, iutx commented
@sfwn PTAL

2024-07-02 05:47 UTC, sfwn reviewed
Handle errors in more detail.

2024-07-02 05:47 UTC, sfwn commented on cmd/erda-server/bootstrap.yaml
> +  cache_size: ${CMP_STEVE_CACHE_SIZE:64}
Note the unit so that others can adjust easily.

2024-07-02 05:47 UTC, sfwn commented on internal/apps/cmp/steve/aggregator.go
> +	if err != nil {
log error is better.

2024-07-02 05:47 UTC, sfwn commented on internal/apps/cmp/steve/aggregator.go
>  		return false, errors.Errorf("steve server not found for cluster %s", clusterName)
missing error detail

2024-07-02 05:47 UTC, sfwn commented on internal/apps/cmp/steve/aggregator.go
>  			return apierrors2.ErrInvoke.InternalError(errors.Errorf("failed to start steve server for cluster %s", clusterInfo.Name))
missing error detail too

2024-07-02 06:56 UTC, sfwn approved these changes

2024-07-02 06:57 UTC, sfwn commented
/approve

2024-07-02 06:57 UTC, merged