fix: add gittar request path encode
erda-project/erda pull request #6302
Opened 2024-03-08 07:30 UTC by Malyue

#### What this PR does / why we need it:
`url` will ignore `#` and the following part. Encode '#' in requests to avoid this

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=572980&iterationID=12783&type=BUG)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  fix: add gittar request path encode            |
| 🇨🇳 中文    |   新增gittar请求路径的编码，以避免#以及后续内容被忽略          |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-03-12 06:54 UTC, sfwn requested changes

2024-03-12 06:54 UTC, sfwn commented on bundle/gittar.go
> +	parts := strings.Split(ref, "/")
Abstract a method and add unit test.

2024-03-13 05:31 UTC, Malyue commented on bundle/gittar.go
> +	parts := strings.Split(ref, "/")
Done.

2024-03-14 06:23 UTC, sfwn approved these changes

2024-03-14 06:24 UTC, sfwn commented
/approve

2024-03-14 06:24 UTC, merged