fix: fix issue with xorm limit(0) causing no data retrieval
erda-project/erda pull request #6306
Opened 2024-03-12 05:52 UTC by Malyue

#### What this PR does / why we need it:
In the newer version of xorm, when using limit(0), the value of 0 is not ignored and will be appended as "LIMIT 0" in the sql. Therefore, special handling is required for cases where the value is 0.

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=573578&iterationID=-1&type=BUG)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  fix: fix xorm limit(0)            |
| 🇨🇳 中文    |  修复xorm limit(0)导致查无数据的问题            |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-03-12 06:53 UTC, sfwn requested changes
Please add unit test for this scenario.

2024-03-13 01:35 UTC, Malyue commented
> Please add unit test for this scenario.

Done.

2024-03-14 05:51 UTC, sfwn approved these changes

2024-03-14 05:52 UTC, sfwn commented
/approve

2024-03-14 05:52 UTC, merged