feat: optimize deploy addon error message alerts
erda-project/erda pull request #6311
Opened 2024-03-14 03:21 UTC by CeerDecy

#### What this PR does / why we need it:

optimize deploy addon error message alerts

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=570070&iterationID=12783&type=TASK)

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       optimize deploy addon error message alerts       |
| 🇨🇳 中文    |       Addon 部署预检查优化版本提示       |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-03-14 03:23 UTC, iutx approved these changes
LGTM. @sfwn

2024-03-16 14:56 UTC, CeerDecy commented
> @CeerDecy Please ensure the CI process.

done

2024-03-19 05:58 UTC, sfwn requested changes

2024-03-19 05:58 UTC, sfwn commented on internal/tools/orchestrator/services/addon/addon_handler.go
> +			def, ok := addons.GetDefault()
Clearly the main purpose of this code snippet is to obtain the recommendVersion:

```golang
recommendVersion := "-"
if def, ok := addons.GetDefault(); ok {
  recommendVersion = def.Version
}
```

2024-03-21 02:19 UTC, sfwn approved these changes

2024-03-21 02:20 UTC, sfwn commented
/approve

2024-03-21 02:39 UTC, merged