feat: remove license api
erda-project/erda pull request #6322
Opened 2024-03-26 07:29 UTC by CeerDecy

#### What this PR does / why we need it:

forward “remove license” api

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=577752&iterationID=12783&type=TASK)

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      forward “remove license” api        |
| 🇨🇳 中文    |      转发license-agent的“移除License”接口        |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-03-26 07:59 UTC, iutx requested changes
@CeerDecy

2024-03-26 07:59 UTC, iutx commented on internal/core/openapi/legacy/api/apis/license_agent/agent_remove_license_post.go
> +	Path:         "/api/licenses/actions/remove",
/api/licenses/actions 
DELETE method

2024-03-27 02:35 UTC, iutx requested changes
@CeerDecy

2024-03-27 02:35 UTC, iutx commented on apistructs/license_agent.go
> +type RemoveLicenseRequest struct {
Keyword `Remove` rename to `Delete` better.

2024-04-02 03:21 UTC, iutx approved these changes
@sfwn PTAL.

2024-04-02 03:24 UTC, sfwn approved these changes

2024-04-02 03:24 UTC, sfwn commented
/approve

2024-04-02 03:40 UTC, merged