fix(dop):  project report sql injection
erda-project/erda pull request #6397
Opened 2024-07-12 06:17 UTC by chengjoey

#### What this PR does / why we need it:
fix(dop):  project report sql injection

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=611654&iterationID=12783&tab=BUG&type=BUG)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | Fix the bug that project report sql injection             |
| 🇨🇳 中文    |    修复了项目报表sql注入的问题          |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-07-12 10:04 UTC, sfwn requested changes
`.Explain` method has SQL injection vulnerability.

2024-07-15 03:45 UTC, chengjoey commented
> `.Explain` method has SQL injection vulnerability, it handles whole sql at client side once.

added query limition

2024-07-16 08:34 UTC, sfwn requested changes

2024-07-16 08:34 UTC, sfwn commented on internal/apps/dop/providers/project_report/query_test.go
> +				End:   "2024-01-02 00:00:00",
add some cases of sql injection.

2024-07-16 09:48 UTC, chengjoey commented on internal/apps/dop/providers/project_report/query_test.go
> +				End:   "2024-01-02 00:00:00",
done

2024-07-24 01:58 UTC, sfwn approved these changes

2024-07-24 01:58 UTC, sfwn commented
/approve

2024-07-24 02:00 UTC, merged