feat: interlink deployed versions, whether deprecated or not
erda-project/erda pull request #6399
Opened 2024-07-18 05:57 UTC by CeerDecy

#### What this PR does / why we need it:
interlink deployed versions, whether deprecated or not

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=615447&iterationID=-1&type=TASK)

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      interlink deployed versions, whether deprecated or not        |
| 🇨🇳 中文    |       关联已经部署的版本，不管是否被废弃       |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-07-19 01:24 UTC, iutx submitted a review, later dismissed
LGTM
@sfwn  PTAL

2024-07-23 03:15 UTC, iutx submitted a review, later dismissed
LGTM @sfwn

2024-07-24 01:56 UTC, sfwn requested changes

2024-07-24 01:56 UTC, sfwn commented on internal/tools/orchestrator/services/addon/addon.go
> +	if ins, err := a.db.FindTmcInstanceByNameAndCLuster(addonName, cluster); err == nil && ins != nil {
you should handle this error

2024-07-24 05:55 UTC, sfwn approved these changes

2024-07-24 05:55 UTC, sfwn commented
/approve

2024-07-24 05:55 UTC, merged