Feature/dop refactor
erda-project/erda pull request #641
Opened 2021-06-21 11:43 UTC by littlejiancc

#### What type of this PR
/kind feature

#### What this PR does / why we need it:
dop and core-services refactor

2021-06-22 12:01 UTC, sfwn commented
After refactor, unit test Coverage rate from 10.65%  to 10.09%, -0.57%.

2021-06-23 09:50 UTC, sfwn requested changes

2021-06-23 09:50 UTC, sfwn commented on apistructs/application.go
> +	Extra string
Remove this useless field.

2021-06-23 09:58 UTC, littlejiancc commented on apistructs/application.go
> +	Extra string
update to 
``` 
Extra string `json:"-"`
```

2021-06-23 09:59 UTC, sfwn approved these changes

2021-06-23 09:59 UTC, sfwn commented
/approve

2021-06-23 10:12 UTC, merged