feat: update keda to support autoscaling/v2
erda-project/erda pull request #6413
Opened 2024-08-01 05:34 UTC by CeerDecy

#### What this PR does / why we need it:
 update keda to support autoscaling/v2

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=533445&iterationID=12783&type=TASK)

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       update keda to support autoscaling/v2        |
| 🇨🇳 中文    |       更新至Keda 2.14.0 适配 autoscaling/v2       |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-08-13 02:38 UTC, iutx reviewed
Could replace http client to clientgo？ @CeerDecy

2024-08-21 05:19 UTC, iutx submitted a review, later dismissed
LGTM @sfwn

2024-08-23 03:18 UTC, sfwn requested changes

2024-08-23 03:18 UTC, sfwn commented on go.mod
> +require (
merge into one require part.

2024-08-23 03:18 UTC, sfwn commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/k8s.go
> +		if *scaledObj.Spec.MinReplicaCount > 0 && *scaledObj.Spec.MaxReplicaCount > 0 && *scaledObj.Spec.MinReplicaCount < *scaledObj.Spec.MaxReplicaCount {
Should check `scaleObj` is not nil before `*` at client side even if func `convertToKedaScaledObject` always return non-nil value.

2024-08-23 05:21 UTC, sfwn approved these changes

2024-08-23 05:21 UTC, sfwn commented
/approve

2024-08-23 05:36 UTC, merged