Refactored metric and metadata interfaces
erda-project/erda pull request #642
Opened 2021-06-21 12:21 UTC by luoyuctl

#### What type of this PR

/kind feature

#### What this PR does / why we need it:

Refactored metrics query, aggregation, scope, and source data interface.

![image](https://user-images.githubusercontent.com/51604064/122760855-2ae9e680-d2ce-11eb-9fb7-0b075477b574.png)

2021-06-22 02:17 UTC, liuhaoyang requested changes

2021-06-22 02:17 UTC, liuhaoyang commented on conf/msp/msp.yaml
> +erda.msp.tmc.metric:
why is the package named tmc ?

2021-06-22 02:17 UTC, liuhaoyang commented on modules/msp/apm/tmc/tmcconfig/serviceconfig.go
> +type Monitor struct {
Why not use the configuration loading of the provider?

2021-06-28 06:44 UTC, luoyuctl commented
GPG unverified

2021-06-28 06:44 UTC, closed without merging