feat: get terminal params from args
erda-project/erda pull request #6428
Opened 2024-08-29 06:34 UTC by CeerDecy

#### What this PR does / why we need it:
1. get terminal params from args 
2. more logs in `s_instance_info` watcher

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=628274&iterationID=12783&type=TASK)

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       get terminal params from args and more logs in `s_instance_info` watcher        |
| 🇨🇳 中文    |       terminal参数从args中获取，并改造watcher，多输出些日志       |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-08-29 08:47 UTC, CeerDecy commented
the `Terminal` fun difficult to monkey patch, there are too many `http.Request`'s functions

2024-09-04 06:05 UTC, iutx approved these changes
LGTM @sfwn 
New feature need frontend added params.

2024-09-12 01:31 UTC, sfwn requested changes
May need some unit tests :-)

2024-09-12 01:31 UTC, sfwn commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
> +			logrus.Infof("get [currentContainerID] from mainContainer,")
remove the ending comma

2024-09-12 01:31 UTC, sfwn commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
> +				logrus.Infof("lastest instance id %v , others cleared by [prevContainerID]", instances[0].ID)
maybe `latest`

2024-09-12 01:31 UTC, sfwn commented on internal/tools/orchestrator/scheduler/executor/plugins/k8s/instanceinfosync/pod.go
> +				logrus.Infof("lastest instance id %v, others cleared by [currentContainerID]", instances[0].ID)
same

2024-09-12 01:37 UTC, sfwn requested changes

2024-09-12 01:37 UTC, sfwn commented on internal/tools/orchestrator/endpoints/instance.go
> +				if env.Name == "DICE_CLUSTER_NAME" {
you'd better use `apistructs.DICE_CLUSTER_NAME`.
literal string is not recommended.

2024-09-12 01:37 UTC, sfwn commented on internal/tools/orchestrator/scheduler/impl/terminal/terminal.go
> +		orgID, _ = strconv.Atoi(r.Header.Get("org-id"))
httputil.OrgHeader

2024-09-12 01:37 UTC, sfwn commented on internal/tools/orchestrator/scheduler/impl/terminal/terminal.go
> +				UserID:   r.Header.Get("User-ID"),
httputil.userheader

2024-09-12 07:55 UTC, sfwn approved these changes

2024-09-12 07:55 UTC, sfwn commented
/approve

2024-09-12 07:56 UTC, merged

2024-09-12 08:49 UTC, sfwn commented
/approve