fix: dice yaml replace * error
erda-project/erda pull request #6433
Opened 2024-09-10 06:10 UTC by CeerDecy

#### What this PR does / why we need it:

fix dice yaml replace * error

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?id=632619&iterationID=-1&pId=0&type=BUG)

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      fix dice yaml replace * error        |
| 🇨🇳 中文    |      修复dice yaml 替换 * 后导致反序列化错误        |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-09-10 06:36 UTC, iutx submitted a review, later dismissed
LGTM @sfwn

2024-09-10 06:41 UTC, sfwn requested changes

2024-09-10 06:41 UTC, sfwn commented on pkg/parser/diceyml/diceyml.go
> +			value = append(value, '\'')
use `fmt.Sprintf("'%s'")` directly for better understanding.

2024-09-10 07:04 UTC, sfwn approved these changes

2024-09-10 07:05 UTC, sfwn commented
/approve

2024-09-10 07:05 UTC, merged

2024-09-11 02:43 UTC, iutx commented
/cherry-pick release/2.3