fix: init controller-runtime logger
erda-project/erda pull request #6453
Opened 2024-10-16 07:59 UTC by CeerDecy

#### What this PR does / why we need it:
init controller-runtime logger
reference [Github issue](https://github.com/rook/rook/issues/12434)

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=641448&iterationID=-1&type=BUG)

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       init controller-runtime logger       |
| 🇨🇳 中文    |      修复controller-runtime报错        |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

2024-10-16 08:01 UTC, iutx submitted a review, later dismissed
LGTM @sfwn

2024-10-17 05:46 UTC, sfwn requested changes

2024-10-17 05:46 UTC, sfwn commented on go.mod
> +require github.com/sykesm/zap-logfmt v0.0.4 // indirect
move into upper require block

2024-10-17 05:49 UTC, CeerDecy commented on go.mod
> +require github.com/sykesm/zap-logfmt v0.0.4 // indirect
done

2024-10-17 07:23 UTC, sfwn approved these changes

2024-10-17 07:24 UTC, sfwn commented
/approve

2024-10-17 07:24 UTC, merged