personal message for issue
erda-project/erda pull request #758
Opened 2021-07-02 11:22 UTC by QvodSoldier

#### What type of this PR
/kind feature

#### What this PR does / why we need it:
add personal message for issue subscriber

#### Which issue(s) this PR fixes:
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=57395&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=REQUIREMENT)

#### Specified Reviewers:

/assign @Effet

2021-07-02 15:00 UTC, Effet requested changes

2021-07-02 15:00 UTC, Effet commented on apistructs/event.go
> +	logrus.Infof("issueEmailContent is: %s", params["issueEmailContent"])
should be debug level

2021-07-04 00:41 UTC, QvodSoldier commented on modules/core-services/services/mbox/mbox.go
> +	mbox.CreatedAt = time.Now()
The newly created duplicate mbox needs to be folded and displayed, and sorted according to the latest creation time.

2021-07-04 00:41 UTC, QvodSoldier commented on modules/dop/dao/issue.go
> +	subscribers, _ := client.GetIssueSubscribersSliceByIssueID(issueID)
done

2021-07-04 00:41 UTC, QvodSoldier commented on modules/dop/services/issuestream/issue_stream.go
> +		logrus.Infof("old content is: %s", content)
done

2021-07-04 00:41 UTC, QvodSoldier commented on modules/dop/services/issue/issue.go
> +	if err := svc.db.BatchCreateIssueSubscribers(subscribes); err != nil {
done

2021-07-04 00:41 UTC, QvodSoldier commented on modules/dop/services/issue/issue.go
> +	if err := svc.db.BatchDeleteIssueSubscribers(req.IssueID, needDeletedSubscribers); err != nil {
done

2021-07-04 00:42 UTC, QvodSoldier commented on modules/dop/services/issue/issue.go
> +		logrus.Infof("is: why????")
hhhhh, why. done

2021-07-04 00:42 UTC, QvodSoldier commented on modules/core-services/dao/mbox.go
> +	query = query.Order("created_at desc").Select("id,title,status,label,created_at,read_at,deduplicate_id,unread_count")
The old code is like this, so I didn’t change it

2021-07-04 00:43 UTC, QvodSoldier commented on modules/core-services/model/mbox.go
> +	// The UnreadCount not null only when DeduplicateID isn't null
done

2021-07-04 00:45 UTC, QvodSoldier commented on apistructs/event.go
> +	logrus.Infof("content is: %s", content)
done

2021-07-04 00:46 UTC, QvodSoldier commented on apistructs/event.go
> +	logrus.Infof("issueEmailContent is: %s", params["issueEmailContent"])
done

2021-07-04 00:54 UTC, QvodSoldier commented
My network is broken, i will push in at night.

2021-07-04 00:57 UTC, QvodSoldier commented
i already push it

2021-07-04 05:55 UTC, Effet requested changes
there are remain not resolved

2021-07-05 02:21 UTC, QvodSoldier commented on modules/dop/endpoints/issue_stream.go
> +		istParam.UserName = user.Name
done

2021-07-05 02:22 UTC, QvodSoldier commented on modules/dop/endpoints/issue_callback.go
> +	logrus.Infof("params of issue event is: %v", params)
done

2021-07-05 02:32 UTC, Effet approved these changes

2021-07-05 02:33 UTC, Effet commented
/approve

2021-07-05 02:50 UTC, merged