action spec adds the execution selector field, and the pipeline selects the executor according to the field
erda-project/erda pull request #969
Opened 2021-07-14 08:45 UTC by kakj-go

#### What type of this PR
/kind feature

#### What this PR does / why we need it:

The apitest task will use the apitest executor when it is executed, but version 1.0 should use the schduler executor, version 2.0 only use the apitest executor, so the executor selection field is added to the action spec, and subsequent actions can choose the executor by themselves

action spec add field like: 
```yaml
executor:
  executorKind: "APITEST"
  executorName: "api-test"
```

2021-07-14 09:18 UTC, sfwn requested changes

2021-07-14 09:18 UTC, sfwn commented on apistructs/extention.go
> +	ExecutorKind string `json:"executorKind" yaml:"executorKind"`
Just `Kind` / `Name` is enough.

2021-07-14 09:18 UTC, sfwn commented on modules/pipeline/services/pipelinesvc/create.go
> -// passedDataWhenCreate stores data passed recursively when create graph.
Put these adjustment into another pr. DO NOT mix it.

2021-07-14 09:23 UTC, sfwn commented
Add erda issue link to PR description please.

And in related PRs, you should link this PR.
![image](https://user-images.githubusercontent.com/13919034/125597886-02389578-f80d-4414-9d51-80de9c7ffce9.png)

See the effect:
![image](https://user-images.githubusercontent.com/13919034/125597860-30ef048f-ec5c-49a4-a1f7-fcf9756d6e47.png)

2021-07-14 09:31 UTC, kakj-go commented
This pr [erda-project(erda-actions#93)](https://github.com/erda-project/erda-actions/pull/93) needs to be merged together

2021-07-14 09:35 UTC, kakj-go commented
link issue: [erda-issues](https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=73326&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMjAyMCIsIjEwMDA1NjAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

2021-07-14 12:29 UTC, sfwn requested changes

2021-07-14 12:29 UTC, sfwn commented on modules/pipeline/services/pipelinesvc/create_task.go
> +func (s *PipelineSvc) judgeTaskExecutor(action *pipelineyml.Action, actionSpec *apistructs.ActionSpec) (spec.PipelineTaskExecutorKind, spec.PipelineTaskExecutorName, error) {
Polish code to multi lines.

2021-07-14 12:29 UTC, sfwn commented on modules/pipeline/services/pipelinesvc/create_task.go
> +func (s *PipelineSvc) judgeTaskExecutor(action *pipelineyml.Action, actionSpec *apistructs.ActionSpec) (spec.PipelineTaskExecutorKind, spec.PipelineTaskExecutorName, error) {
string = ""

2021-07-14 12:30 UTC, sfwn approved these changes

2021-07-14 12:31 UTC, sfwn commented
/approve

2021-07-14 13:42 UTC, merged

2021-07-15 02:03 UTC, kakj-go commented
/cherry-pick release/1.1

2021-07-15 02:26 UTC, kakj-go commented
/cherry-pick release/1.1